puts "Eliminando ciudades anteriores"
Ciudad.delete_all

ciudades = [
  {"departamento"=>"Antioquia", "id"=>5001, "nombre"=>"MEDELLIN"},
  {"departamento"=>"Antioquia", "id"=>5002, "nombre"=>"ABEJORRAL"},
  {"departamento"=>"Antioquia", "id"=>5004, "nombre"=>"ABRIAQU"},
  {"departamento"=>"Antioquia", "id"=>5021, "nombre"=>"ALEJANDRIA"},
  {"departamento"=>"Antioquia", "id"=>5030, "nombre"=>"AMAGA"},
  {"departamento"=>"Antioquia", "id"=>5031, "nombre"=>"AMALFI"},
  {"departamento"=>"Antioquia", "id"=>5034, "nombre"=>"ANDES"},
  {"departamento"=>"Antioquia", "id"=>5036, "nombre"=>"ANGELOPOLIS"},
  {"departamento"=>"Antioquia", "id"=>5038, "nombre"=>"ANGOSTURA"},
  {"departamento"=>"Antioquia", "id"=>5040, "nombre"=>"ANOR"},
  {"departamento"=>"Antioquia", "id"=>5042, "nombre"=>"SANTAFE DE ANTIOQUIA"},
  {"departamento"=>"Antioquia", "id"=>5044, "nombre"=>"ANZA"},
  {"departamento"=>"Antioquia", "id"=>5045, "nombre"=>"APARTADO"},
  {"departamento"=>"Antioquia", "id"=>5051, "nombre"=>"ARBOLETES"},
  {"departamento"=>"Antioquia", "id"=>5055, "nombre"=>"ARGELIA"},
  {"departamento"=>"Antioquia", "id"=>5059, "nombre"=>"ARMENIA"},
  {"departamento"=>"Antioquia", "id"=>5079, "nombre"=>"BARBOSA"},
  {"departamento"=>"Antioquia", "id"=>5086, "nombre"=>"BELMIRA"},
  {"departamento"=>"Antioquia", "id"=>5088, "nombre"=>"BELLO"},
  {"departamento"=>"Antioquia", "id"=>5091, "nombre"=>"BETANIA"},
  {"departamento"=>"Antioquia", "id"=>5093, "nombre"=>"BETULIA"},
  {"departamento"=>"Antioquia", "id"=>5101, "nombre"=>"CIUDAD BOLIVAR"},
  {"departamento"=>"Antioquia", "id"=>5107, "nombre"=>"BRICEÑO"},
  {"departamento"=>"Antioquia", "id"=>5113, "nombre"=>"BURITICA"},
  {"departamento"=>"Antioquia", "id"=>5120, "nombre"=>"CACERES"},
  {"departamento"=>"Antioquia", "id"=>5125, "nombre"=>"CAICEDO"},
  {"departamento"=>"Antioquia", "id"=>5129, "nombre"=>"CALDAS"},
  {"departamento"=>"Antioquia", "id"=>5134, "nombre"=>"CAMPAMENTO"},
  {"departamento"=>"Antioquia", "id"=>5138, "nombre"=>"CAÑAS GORDAS"},
  {"departamento"=>"Antioquia", "id"=>5142, "nombre"=>"CARACOL"},
  {"departamento"=>"Antioquia", "id"=>5145, "nombre"=>"CARAMANTA"},
  {"departamento"=>"Antioquia", "id"=>5147, "nombre"=>"CAREPA"},
  {"departamento"=>"Antioquia", "id"=>5148, "nombre"=>"EL CARMEN DE VIBORAL"},
  {"departamento"=>"Antioquia", "id"=>5150, "nombre"=>"CAROLINA"},
  {"departamento"=>"Antioquia", "id"=>5154, "nombre"=>"CAUCASIA"},
  {"departamento"=>"Antioquia", "id"=>5172, "nombre"=>"CHIGORODO"},
  {"departamento"=>"Antioquia", "id"=>5190, "nombre"=>"CISNEROS"},
  {"departamento"=>"Antioquia", "id"=>5197, "nombre"=>"COCORNA"},
  {"departamento"=>"Antioquia", "id"=>5206, "nombre"=>"CONCEPCION"},
  {"departamento"=>"Antioquia", "id"=>5209, "nombre"=>"CONCORDIA"},
  {"departamento"=>"Antioquia", "id"=>5212, "nombre"=>"COPACABANA"},
  {"departamento"=>"Antioquia", "id"=>5234, "nombre"=>"DABEIBA"},
  {"departamento"=>"Antioquia", "id"=>5237, "nombre"=>"DON MATIAS"},
  {"departamento"=>"Antioquia", "id"=>5240, "nombre"=>"EBEJICO"},
  {"departamento"=>"Antioquia", "id"=>5250, "nombre"=>"EL BAGRE"},
  {"departamento"=>"Antioquia", "id"=>5264, "nombre"=>"ENTRERRIOS"},
  {"departamento"=>"Antioquia", "id"=>5266, "nombre"=>"ENVIGADO"},
  {"departamento"=>"Antioquia", "id"=>5282, "nombre"=>"FREDONIA"},
  {"departamento"=>"Antioquia", "id"=>5284, "nombre"=>"FRONTINO"},
  {"departamento"=>"Antioquia", "id"=>5306, "nombre"=>"GIRALDO"},
  {"departamento"=>"Antioquia", "id"=>5308, "nombre"=>"GIRARDOTA"},
  {"departamento"=>"Antioquia", "id"=>5310, "nombre"=>"GOMEZ PLATA"},
  {"departamento"=>"Antioquia", "id"=>5313, "nombre"=>"GRANADA"},
  {"departamento"=>"Antioquia", "id"=>5315, "nombre"=>"GUADALUPE"},
  {"departamento"=>"Antioquia", "id"=>5318, "nombre"=>"GUARNE"},
  {"departamento"=>"Antioquia", "id"=>5321, "nombre"=>"GUATAPE"},
  {"departamento"=>"Antioquia", "id"=>5347, "nombre"=>"HELICONIA"},
  {"departamento"=>"Antioquia", "id"=>5353, "nombre"=>"HISPANIA"},
  {"departamento"=>"Antioquia", "id"=>5360, "nombre"=>"ITAGUI"},
  {"departamento"=>"Antioquia", "id"=>5361, "nombre"=>"ITUANGO"},
  {"departamento"=>"Antioquia", "id"=>5364, "nombre"=>"JARDIN"},
  {"departamento"=>"Antioquia", "id"=>5368, "nombre"=>"JERICO"},
  {"departamento"=>"Antioquia", "id"=>5376, "nombre"=>"LA CEJA"},
  {"departamento"=>"Antioquia", "id"=>5380, "nombre"=>"LA ESTRELLA"},
  {"departamento"=>"Antioquia", "id"=>5390, "nombre"=>"LA PINTADA"},
  {"departamento"=>"Antioquia", "id"=>5400, "nombre"=>"LA UNION"},
  {"departamento"=>"Antioquia", "id"=>5411, "nombre"=>"LIBORINA"},
  {"departamento"=>"Antioquia", "id"=>5425, "nombre"=>"MACEO"},
  {"departamento"=>"Antioquia", "id"=>5440, "nombre"=>"MARINILLA"},
  {"departamento"=>"Antioquia", "id"=>5467, "nombre"=>"MONTEBELLO"},
  {"departamento"=>"Antioquia", "id"=>5475, "nombre"=>"MURINDO"},
  {"departamento"=>"Antioquia", "id"=>5480, "nombre"=>"MUTATA"},
  {"departamento"=>"Antioquia", "id"=>5483, "nombre"=>"NARIÑO"},
  {"departamento"=>"Antioquia", "id"=>5490, "nombre"=>"NECOCLI"},
  {"departamento"=>"Antioquia", "id"=>5495, "nombre"=>"NECHI"},
  {"departamento"=>"Antioquia", "id"=>5501, "nombre"=>"OLAYA"},
  {"departamento"=>"Antioquia", "id"=>5541, "nombre"=>"PEÑOL"},
  {"departamento"=>"Antioquia", "id"=>5543, "nombre"=>"PEQUE"},
  {"departamento"=>"Antioquia", "id"=>5576, "nombre"=>"PUEBLORRICO"},
  {"departamento"=>"Antioquia", "id"=>5579, "nombre"=>"PUERTO BERRIO"},
  {"departamento"=>"Antioquia", "id"=>5585, "nombre"=>"PUERTO NARE"},
  {"departamento"=>"Antioquia", "id"=>5591, "nombre"=>"PUERTO TRIUNFO"},
  {"departamento"=>"Antioquia", "id"=>5604, "nombre"=>"REMEDIOS"},
  {"departamento"=>"Antioquia", "id"=>5607, "nombre"=>"RETIRO"},
  {"departamento"=>"Antioquia", "id"=>5615, "nombre"=>"RIONEGRO"},
  {"departamento"=>"Antioquia", "id"=>5628, "nombre"=>"SABANALARGA"},
  {"departamento"=>"Antioquia", "id"=>5631, "nombre"=>"SABANETA"},
  {"departamento"=>"Antioquia", "id"=>5642, "nombre"=>"SALGAR"},
  {"departamento"=>"Antioquia", "id"=>5647, "nombre"=>"SAN ANDRES"},
  {"departamento"=>"Antioquia", "id"=>5649, "nombre"=>"SAN CARLOS"},
  {"departamento"=>"Antioquia", "id"=>5652, "nombre"=>"SAN FRANCISCO"},
  {"departamento"=>"Antioquia", "id"=>5656, "nombre"=>"SAN JERONIMO"},
  {"departamento"=>"Antioquia", "id"=>5658, "nombre"=>"SAN JOSE DE LA MONTAÑA"},
  {"departamento"=>"Antioquia", "id"=>5659, "nombre"=>"SAN JUAN DE URABA"},
  {"departamento"=>"Antioquia", "id"=>5660, "nombre"=>"SAN LUIS"},
  {"departamento"=>"Antioquia", "id"=>5664, "nombre"=>"SAN PEDRO"},
  {"departamento"=>"Antioquia", "id"=>5665, "nombre"=>"SAN PEDRO DE URABA"},
  {"departamento"=>"Antioquia", "id"=>5667, "nombre"=>"SAN RAFAEL"},
  {"departamento"=>"Antioquia", "id"=>5670, "nombre"=>"SAN ROQUE"},
  {"departamento"=>"Antioquia", "id"=>5674, "nombre"=>"SAN VICENTE"},
  {"departamento"=>"Antioquia", "id"=>5679, "nombre"=>"SANTA BARBARA"},
  {"departamento"=>"Antioquia", "id"=>5686, "nombre"=>"SANTA ROSA DE OSOS"},
  {"departamento"=>"Antioquia", "id"=>5690, "nombre"=>"SANTO DOMINGO"},
  {"departamento"=>"Antioquia", "id"=>5697, "nombre"=>"EL SANTUARIO"},
  {"departamento"=>"Antioquia", "id"=>5736, "nombre"=>"SEGOVIA"},
  {"departamento"=>"Antioquia", "id"=>5756, "nombre"=>"SONSON"},
  {"departamento"=>"Antioquia", "id"=>5761, "nombre"=>"SOPETRAN"},
  {"departamento"=>"Antioquia", "id"=>5789, "nombre"=>"TAMESIS"},
  {"departamento"=>"Antioquia", "id"=>5790, "nombre"=>"TARAZA"},
  {"departamento"=>"Antioquia", "id"=>5792, "nombre"=>"TARSO"},
  {"departamento"=>"Antioquia", "id"=>5809, "nombre"=>"TITIRIBI"},
  {"departamento"=>"Antioquia", "id"=>5819, "nombre"=>"TOLEDO"},
  {"departamento"=>"Antioquia", "id"=>5837, "nombre"=>"TURBO"},
  {"departamento"=>"Antioquia", "id"=>5842, "nombre"=>"URAMITA"},
  {"departamento"=>"Antioquia", "id"=>5847, "nombre"=>"URRAO"},
  {"departamento"=>"Antioquia", "id"=>5854, "nombre"=>"VALDIVIA"},
  {"departamento"=>"Antioquia", "id"=>5856, "nombre"=>"VALPARAISO"},
  {"departamento"=>"Antioquia", "id"=>5858, "nombre"=>"VEGACHI"},
  {"departamento"=>"Antioquia", "id"=>5861, "nombre"=>"VENECIA"},
  {"departamento"=>"Antioquia", "id"=>5873, "nombre"=>"VIGIA DEL FUERTE"},
  {"departamento"=>"Antioquia", "id"=>5885, "nombre"=>"YALI"},
  {"departamento"=>"Antioquia", "id"=>5887, "nombre"=>"YARUMAL"},
  {"departamento"=>"Antioquia", "id"=>5890, "nombre"=>"YOLOMBO"},
  {"departamento"=>"Antioquia", "id"=>5893, "nombre"=>"YONDO"},
  {"departamento"=>"Antioquia", "id"=>5895, "nombre"=>"ZARAGOZA"},
  {"departamento"=>"Atlantico", "id"=>8001, "nombre"=>"BARRANQUILLA"},
  {"departamento"=>"Atlantico", "id"=>8078, "nombre"=>"BARANOA"},
  {"departamento"=>"Atlantico", "id"=>8137, "nombre"=>"CAMPO DE LA CRUZ"},
  {"departamento"=>"Atlantico", "id"=>8141, "nombre"=>"CANDELARIA"},
  {"departamento"=>"Atlantico", "id"=>8296, "nombre"=>"GALAPA"},
  {"departamento"=>"Atlantico", "id"=>8372, "nombre"=>"JUAN DE ACOSTA"},
  {"departamento"=>"Atlantico", "id"=>8421, "nombre"=>"LURUACO"},
  {"departamento"=>"Atlantico", "id"=>8433, "nombre"=>"MALAMBO"},
  {"departamento"=>"Atlantico", "id"=>8436, "nombre"=>"MANATI"},
  {"departamento"=>"Atlantico", "id"=>8520, "nombre"=>"PALMAR DE VARELA"},
  {"departamento"=>"Atlantico", "id"=>8549, "nombre"=>"PIOJO"},
  {"departamento"=>"Atlantico", "id"=>8558, "nombre"=>"POLONUEVO"},
  {"departamento"=>"Atlantico", "id"=>8560, "nombre"=>"PONEDERA"},
  {"departamento"=>"Atlantico", "id"=>8573, "nombre"=>"PUERTO COLOMBIA"},
  {"departamento"=>"Atlantico", "id"=>8606, "nombre"=>"REPEL"},
  {"departamento"=>"Atlantico", "id"=>8634, "nombre"=>"SABANAGRANDE"},
  {"departamento"=>"Atlantico", "id"=>8638, "nombre"=>"SABANALARGA"},
  {"departamento"=>"Atlantico", "id"=>8675, "nombre"=>"SANTA LUCIA"},
  {"departamento"=>"Atlantico", "id"=>8685, "nombre"=>"SANTO TOMAS"},
  {"departamento"=>"Atlantico", "id"=>8758, "nombre"=>"SOLEDAD"},
  {"departamento"=>"Atlantico", "id"=>8770, "nombre"=>"SUAN"},
  {"departamento"=>"Atlantico", "id"=>8832, "nombre"=>"TUBARA"},
  {"departamento"=>"Atlantico", "id"=>8849, "nombre"=>"USIACUR"},
  {"departamento"=>"Bogota D.C", "id"=>11001, "nombre"=>"BOGOTA"},
  {"departamento"=>"Bolivar", "id"=>13001, "nombre"=>"CARTAGENA"},
  {"departamento"=>"Bolivar", "id"=>13006, "nombre"=>"ACHI"},
  {"departamento"=>"Bolivar", "id"=>13030, "nombre"=>"ALTOS DEL ROSARIO"},
  {"departamento"=>"Bolivar", "id"=>13042, "nombre"=>"ARENAL"},
  {"departamento"=>"Bolivar", "id"=>13052, "nombre"=>"ARJONA"},
  {"departamento"=>"Bolivar", "id"=>13062, "nombre"=>"ARROYOHONDO"},
  {"departamento"=>"Bolivar", "id"=>13074, "nombre"=>"BARRANCO DE LOBA"},
  {"departamento"=>"Bolivar", "id"=>13140, "nombre"=>"CALAMAR"},
  {"departamento"=>"Bolivar", "id"=>13160, "nombre"=>"CANTAGALLO"},
  {"departamento"=>"Bolivar", "id"=>13188, "nombre"=>"CICUCO"},
  {"departamento"=>"Bolivar", "id"=>13212, "nombre"=>"CORDOBA"},
  {"departamento"=>"Bolivar", "id"=>13222, "nombre"=>"CLEMENCIA"},
  {"departamento"=>"Bolivar", "id"=>13244, "nombre"=>"EL CARMEN DE BOLIVAR"},
  {"departamento"=>"Bolivar", "id"=>13248, "nombre"=>"EL GUAMO"},
  {"departamento"=>"Bolivar", "id"=>13268, "nombre"=>"EL PEO"},
  {"departamento"=>"Bolivar", "id"=>13300, "nombre"=>"HATILLO DE LOBA"},
  {"departamento"=>"Bolivar", "id"=>13430, "nombre"=>"MAGANGUE"},
  {"departamento"=>"Bolivar", "id"=>13433, "nombre"=>"MAHATES"},
  {"departamento"=>"Bolivar", "id"=>13440, "nombre"=>"MARGARITA"},
  {"departamento"=>"Bolivar", "id"=>13442, "nombre"=>"MARIA LA BAJA"},
  {"departamento"=>"Bolivar", "id"=>13458, "nombre"=>"MONTECRISTO"},
  {"departamento"=>"Bolivar", "id"=>13468, "nombre"=>"MOMPOS"},
  {"departamento"=>"Bolivar", "id"=>13473, "nombre"=>"MORALES"},
  {"departamento"=>"Bolivar", "id"=>13549, "nombre"=>"PINILLOS"},
  {"departamento"=>"Bolivar", "id"=>13580, "nombre"=>"REGIDOR"},
  {"departamento"=>"Bolivar", "id"=>13600, "nombre"=>"RIO VIEJO"},
  {"departamento"=>"Bolivar", "id"=>13620, "nombre"=>"SAN CRISTOBAL"},
  {"departamento"=>"Bolivar", "id"=>13647, "nombre"=>"SAN ESTANISLAO"},
  {"departamento"=>"Bolivar", "id"=>13650, "nombre"=>"SAN FERNANDO"},
  {"departamento"=>"Bolivar", "id"=>13654, "nombre"=>"SAN JACINTO"},
  {"departamento"=>"Bolivar", "id"=>13655, "nombre"=>"SAN JACINTO DEL CAUCA"},
  {"departamento"=>"Bolivar", "id"=>13657, "nombre"=>"SAN JUAN NEPOMUCENO"},
  {"departamento"=>"Bolivar", "id"=>13667, "nombre"=>"SAN MARTIN DE LOBA"},
  {"departamento"=>"Bolivar", "id"=>13670, "nombre"=>"SAN PABLO"},
  {"departamento"=>"Bolivar", "id"=>13673, "nombre"=>"SANTA CATALINA"},
  {"departamento"=>"Bolivar", "id"=>13683, "nombre"=>"SANTA ROSA"},
  {"departamento"=>"Bolivar", "id"=>13688, "nombre"=>"SANTA ROSA DEL SUR"},
  {"departamento"=>"Bolivar", "id"=>13744, "nombre"=>"SIMITI"},
  {"departamento"=>"Bolivar", "id"=>13760, "nombre"=>"SOPLAVIENTO"},
  {"departamento"=>"Bolivar", "id"=>13780, "nombre"=>"TALAIGUA NUEVO"},
  {"departamento"=>"Bolivar", "id"=>13810, "nombre"=>"TIQUISIO"},
  {"departamento"=>"Bolivar", "id"=>13836, "nombre"=>"TURBACO"},
  {"departamento"=>"Bolivar", "id"=>13838, "nombre"=>"TURBANA"},
  {"departamento"=>"Bolivar", "id"=>13873, "nombre"=>"VILLANUEVA"},
  {"departamento"=>"Bolivar", "id"=>13894, "nombre"=>"ZAMBRANO"},
  {"departamento"=>"Boyaca", "id"=>15001, "nombre"=>"TUNJA"},
  {"departamento"=>"Boyaca", "id"=>15022, "nombre"=>"ALMEIDA"},
  {"departamento"=>"Boyaca", "id"=>15047, "nombre"=>"AQUITANIA"},
  {"departamento"=>"Boyaca", "id"=>15051, "nombre"=>"ARCABUCO"},
  {"departamento"=>"Boyaca", "id"=>15087, "nombre"=>"BELEN"},
  {"departamento"=>"Boyaca", "id"=>15090, "nombre"=>"BERBEO"},
  {"departamento"=>"Boyaca", "id"=>15092, "nombre"=>"BETEITIVA"},
  {"departamento"=>"Boyaca", "id"=>15097, "nombre"=>"BOAVITA"},
  {"departamento"=>"Boyaca", "id"=>15104, "nombre"=>"BOYACA"},
  {"departamento"=>"Boyaca", "id"=>15106, "nombre"=>"BRICEÑO"},
  {"departamento"=>"Boyaca", "id"=>15109, "nombre"=>"BUENAVISTA"},
  {"departamento"=>"Boyaca", "id"=>15114, "nombre"=>"BUSBANZA"},
  {"departamento"=>"Boyaca", "id"=>15131, "nombre"=>"CALDAS"},
  {"departamento"=>"Boyaca", "id"=>15135, "nombre"=>"CAMPOHERMOSO"},
  {"departamento"=>"Boyaca", "id"=>15162, "nombre"=>"CERINZA"},
  {"departamento"=>"Boyaca", "id"=>15172, "nombre"=>"CHINAVITA"},
  {"departamento"=>"Boyaca", "id"=>15176, "nombre"=>"CHIQUINQUIRA"},
  {"departamento"=>"Boyaca", "id"=>15180, "nombre"=>"CHISCAS"},
  {"departamento"=>"Boyaca", "id"=>15183, "nombre"=>"CHITA"},
  {"departamento"=>"Boyaca", "id"=>15185, "nombre"=>"CHITARAQUE"},
  {"departamento"=>"Boyaca", "id"=>15187, "nombre"=>"CHIVATA"},
  {"departamento"=>"Boyaca", "id"=>15189, "nombre"=>"CIENEGA"},
  {"departamento"=>"Boyaca", "id"=>15204, "nombre"=>"COMBITA"},
  {"departamento"=>"Boyaca", "id"=>15212, "nombre"=>"COPER"},
  {"departamento"=>"Boyaca", "id"=>15215, "nombre"=>"CORRALES"},
  {"departamento"=>"Boyaca", "id"=>15218, "nombre"=>"COVARACH?A"},
  {"departamento"=>"Boyaca", "id"=>15223, "nombre"=>"CUBARA"},
  {"departamento"=>"Boyaca", "id"=>15224, "nombre"=>"CUCAITA"},
  {"departamento"=>"Boyaca", "id"=>15226, "nombre"=>"CUITIVA"},
  {"departamento"=>"Boyaca", "id"=>15232, "nombre"=>"CHIQUIZA"},
  {"departamento"=>"Boyaca", "id"=>15236, "nombre"=>"CHIVOR"},
  {"departamento"=>"Boyaca", "id"=>15238, "nombre"=>"DUITAMA"},
  {"departamento"=>"Boyaca", "id"=>15244, "nombre"=>"EL COCUY"},
  {"departamento"=>"Boyaca", "id"=>15248, "nombre"=>"EL ESPINO"},
  {"departamento"=>"Boyaca", "id"=>15272, "nombre"=>"FIRAVITOBA"},
  {"departamento"=>"Boyaca", "id"=>15276, "nombre"=>"FLORESTA"},
  {"departamento"=>"Boyaca", "id"=>15293, "nombre"=>"GACHANTIVA"},
  {"departamento"=>"Boyaca", "id"=>15296, "nombre"=>"GAMEZA"},
  {"departamento"=>"Boyaca", "id"=>15299, "nombre"=>"GARAGOA"},
  {"departamento"=>"Boyaca", "id"=>15317, "nombre"=>"GUACAMAYAS"},
  {"departamento"=>"Boyaca", "id"=>15322, "nombre"=>"GUATEQUE"},
  {"departamento"=>"Boyaca", "id"=>15325, "nombre"=>"GUAYAT?"},
  {"departamento"=>"Boyaca", "id"=>15332, "nombre"=>"G?IC?N"},
  {"departamento"=>"Boyaca", "id"=>15362, "nombre"=>"IZA"},
  {"departamento"=>"Boyaca", "id"=>15367, "nombre"=>"JENESANO"},
  {"departamento"=>"Boyaca", "id"=>15368, "nombre"=>"JERIC"},
  {"departamento"=>"Boyaca", "id"=>15377, "nombre"=>"LABRANZAGRANDE"},
  {"departamento"=>"Boyaca", "id"=>15380, "nombre"=>"LA CAPILLA"},
  {"departamento"=>"Boyaca", "id"=>15401, "nombre"=>"LA VICTORIA"},
  {"departamento"=>"Boyaca", "id"=>15403, "nombre"=>"LA UVITA"},
  {"departamento"=>"Boyaca", "id"=>15407, "nombre"=>"VILLA DE LEYVA"},
  {"departamento"=>"Boyaca", "id"=>15425, "nombre"=>"MACANAL"},
  {"departamento"=>"Boyaca", "id"=>15442, "nombre"=>"MARIP"},
  {"departamento"=>"Boyaca", "id"=>15455, "nombre"=>"MIRAFLORES"},
  {"departamento"=>"Boyaca", "id"=>15464, "nombre"=>"MONGUA"},
  {"departamento"=>"Boyaca", "id"=>15466, "nombre"=>"MONGU"},
  {"departamento"=>"Boyaca", "id"=>15469, "nombre"=>"MONIQUIR?"},
  {"departamento"=>"Boyaca", "id"=>15476, "nombre"=>"MOTAVITA"},
  {"departamento"=>"Boyaca", "id"=>15480, "nombre"=>"MUZO"},
  {"departamento"=>"Boyaca", "id"=>15491, "nombre"=>"NOBSA"},
  {"departamento"=>"Boyaca", "id"=>15494, "nombre"=>"NUEVO COL"},
  {"departamento"=>"Boyaca", "id"=>15500, "nombre"=>"OICAT?"},
  {"departamento"=>"Boyaca", "id"=>15507, "nombre"=>"OTANCHE"},
  {"departamento"=>"Boyaca", "id"=>15511, "nombre"=>"PACHAVITA"},
  {"departamento"=>"Boyaca", "id"=>15514, "nombre"=>"P?EZ"},
  {"departamento"=>"Boyaca", "id"=>15516, "nombre"=>"PAIPA"},
  {"departamento"=>"Boyaca", "id"=>15518, "nombre"=>"PAJARITO"},
  {"departamento"=>"Boyaca", "id"=>15522, "nombre"=>"PANQUEBA"},
  {"departamento"=>"Boyaca", "id"=>15531, "nombre"=>"PAUNA"},
  {"departamento"=>"Boyaca", "id"=>15533, "nombre"=>"PAYA"},
  {"departamento"=>"Boyaca", "id"=>15537, "nombre"=>"PAZ DE R?O"},
  {"departamento"=>"Boyaca", "id"=>15542, "nombre"=>"PESCA"},
  {"departamento"=>"Boyaca", "id"=>15550, "nombre"=>"PISBA"},
  {"departamento"=>"Boyaca", "id"=>15572, "nombre"=>"PUERTO BOyaca"},
  {"departamento"=>"Boyaca", "id"=>15580, "nombre"=>"QU?PAMA"},
  {"departamento"=>"Boyaca", "id"=>15599, "nombre"=>"RAMIRIQU"},
  {"departamento"=>"Boyaca", "id"=>15600, "nombre"=>"R?QUIRA"},
  {"departamento"=>"Boyaca", "id"=>15621, "nombre"=>"ROND"},
  {"departamento"=>"Boyaca", "id"=>15632, "nombre"=>"SABOY?"},
  {"departamento"=>"Boyaca", "id"=>15638, "nombre"=>"S?CHICA"},
  {"departamento"=>"Boyaca", "id"=>15646, "nombre"=>"SAMAC?"},
  {"departamento"=>"Boyaca", "id"=>15660, "nombre"=>"SAN EDUARDO"},
  {"departamento"=>"Boyaca", "id"=>15664, "nombre"=>"SAN JOS? DE PARE"},
  {"departamento"=>"Boyaca", "id"=>15667, "nombre"=>"SAN LUIS DE GACENO"},
  {"departamento"=>"Boyaca", "id"=>15673, "nombre"=>"SAN MATEO"},
  {"departamento"=>"Boyaca", "id"=>15676, "nombre"=>"SAN MIGUEL DE SEMA"},
  {"departamento"=>"Boyaca", "id"=>15681, "nombre"=>"SAN PABLO DE BORBUR"},
  {"departamento"=>"Boyaca", "id"=>15686, "nombre"=>"SANTANA"},
  {"departamento"=>"Boyaca", "id"=>15690, "nombre"=>"SANTA MAR?A"},
  {"departamento"=>"Boyaca", "id"=>15693, "nombre"=>"SANTA ROSA DE VITERBO"},
  {"departamento"=>"Boyaca", "id"=>15696, "nombre"=>"SANTA SOF?A"},
  {"departamento"=>"Boyaca", "id"=>15720, "nombre"=>"SATIVANORTE"},
  {"departamento"=>"Boyaca", "id"=>15723, "nombre"=>"SATIVASUR"},
  {"departamento"=>"Boyaca", "id"=>15740, "nombre"=>"SIACHOQUE"},
  {"departamento"=>"Boyaca", "id"=>15753, "nombre"=>"SOAT?"},
  {"departamento"=>"Boyaca", "id"=>15755, "nombre"=>"SOCOT?"},
  {"departamento"=>"Boyaca", "id"=>15757, "nombre"=>"SOCHA"},
  {"departamento"=>"Boyaca", "id"=>15759, "nombre"=>"SOGAMOSO"},
  {"departamento"=>"Boyaca", "id"=>15761, "nombre"=>"SOMONDOCO"},
  {"departamento"=>"Boyaca", "id"=>15762, "nombre"=>"SORA"},
  {"departamento"=>"Boyaca", "id"=>15763, "nombre"=>"SOTAQUIR?"},
  {"departamento"=>"Boyaca", "id"=>15764, "nombre"=>"SORAC?"},
  {"departamento"=>"Boyaca", "id"=>15774, "nombre"=>"SUSAC"},
  {"departamento"=>"Boyaca", "id"=>15776, "nombre"=>"SUTAMARCH?N"},
  {"departamento"=>"Boyaca", "id"=>15778, "nombre"=>"SUTATENZA"},
  {"departamento"=>"Boyaca", "id"=>15790, "nombre"=>"TASCO"},
  {"departamento"=>"Boyaca", "id"=>15798, "nombre"=>"TENZA"},
  {"departamento"=>"Boyaca", "id"=>15804, "nombre"=>"TIBAN?"},
  {"departamento"=>"Boyaca", "id"=>15806, "nombre"=>"TIBASOSA"},
  {"departamento"=>"Boyaca", "id"=>15808, "nombre"=>"TINJAC?"},
  {"departamento"=>"Boyaca", "id"=>15810, "nombre"=>"TIPACOQUE"},
  {"departamento"=>"Boyaca", "id"=>15814, "nombre"=>"TOCA"},
  {"departamento"=>"Boyaca", "id"=>15816, "nombre"=>"TOG?"},
  {"departamento"=>"Boyaca", "id"=>15820, "nombre"=>"T?PAGA"},
  {"departamento"=>"Boyaca", "id"=>15822, "nombre"=>"TOTA"},
  {"departamento"=>"Boyaca", "id"=>15832, "nombre"=>"TUNUNGU?"},
  {"departamento"=>"Boyaca", "id"=>15835, "nombre"=>"TURMEQU?"},
  {"departamento"=>"Boyaca", "id"=>15837, "nombre"=>"TUTA"},
  {"departamento"=>"Boyaca", "id"=>15839, "nombre"=>"TUTAZ?"},
  {"departamento"=>"Boyaca", "id"=>15842, "nombre"=>"UMBITA"},
  {"departamento"=>"Boyaca", "id"=>15861, "nombre"=>"VENTAQUEMADA"},
  {"departamento"=>"Boyaca", "id"=>15879, "nombre"=>"VIRACACH?"},
  {"departamento"=>"Boyaca", "id"=>15897, "nombre"=>"ZETAQUIRA"},
  {"departamento"=>"Caldas", "id"=>17001, "nombre"=>"MANIZALES"},
  {"departamento"=>"Caldas", "id"=>17013, "nombre"=>"AGUADAS"},
  {"departamento"=>"Caldas", "id"=>17042, "nombre"=>"ANSERMA"},
  {"departamento"=>"Caldas", "id"=>17050, "nombre"=>"ARANZAZU"},
  {"departamento"=>"Caldas", "id"=>17088, "nombre"=>"BELALC?ZAR"},
  {"departamento"=>"Caldas", "id"=>17174, "nombre"=>"CHINCHIN?"},
  {"departamento"=>"Caldas", "id"=>17272, "nombre"=>"FILADELFIA"},
  {"departamento"=>"Caldas", "id"=>17380, "nombre"=>"LA DORADA"},
  {"departamento"=>"Caldas", "id"=>17388, "nombre"=>"LA MERCED"},
  {"departamento"=>"Caldas", "id"=>17433, "nombre"=>"MANZANARES"},
  {"departamento"=>"Caldas", "id"=>17442, "nombre"=>"MARMATO"},
  {"departamento"=>"Caldas", "id"=>17444, "nombre"=>"MARQUETALIA"},
  {"departamento"=>"Caldas", "id"=>17446, "nombre"=>"MARULANDA"},
  {"departamento"=>"Caldas", "id"=>17486, "nombre"=>"NEIRA"},
  {"departamento"=>"Caldas", "id"=>17495, "nombre"=>"NORCASIA"},
  {"departamento"=>"Caldas", "id"=>17513, "nombre"=>"P?CORA"},
  {"departamento"=>"Caldas", "id"=>17524, "nombre"=>"PALESTINA"},
  {"departamento"=>"Caldas", "id"=>17541, "nombre"=>"PENSILVANIA"},
  {"departamento"=>"Caldas", "id"=>17614, "nombre"=>"RIOSUCIO"},
  {"departamento"=>"Caldas", "id"=>17616, "nombre"=>"RISARALDA"},
  {"departamento"=>"Caldas", "id"=>17653, "nombre"=>"SALAMINA"},
  {"departamento"=>"Caldas", "id"=>17662, "nombre"=>"SAMAN?"},
  {"departamento"=>"Caldas", "id"=>17665, "nombre"=>"SAN JOS?"},
  {"departamento"=>"Caldas", "id"=>17777, "nombre"=>"SUP?A"},
  {"departamento"=>"Caldas", "id"=>17867, "nombre"=>"VICTORIA"},
  {"departamento"=>"Caldas", "id"=>17873, "nombre"=>"VILLAMAR?A"},
  {"departamento"=>"Caldas", "id"=>17877, "nombre"=>"VITERBO"},
  {"departamento"=>"Caquet?", "id"=>18001, "nombre"=>"FLORENCIA"},
  {"departamento"=>"Caquet?", "id"=>18029, "nombre"=>"ALBANIA"},
  {"departamento"=>"Caquet?", "id"=>18094, "nombre"=>"BEL?N DE LOS ANDAQUIES"},
  {"departamento"=>"Caquet?", "id"=>18150, "nombre"=>"CARTAGENA DEL CHAIR?"},
  {"departamento"=>"Caquet?", "id"=>18205, "nombre"=>"CURILLO"},
  {"departamento"=>"Caquet?", "id"=>18247, "nombre"=>"EL DONCELLO"},
  {"departamento"=>"Caquet?", "id"=>18256, "nombre"=>"EL PAUJIL"},
  {"departamento"=>"Caquet?", "id"=>18410, "nombre"=>"LA MONTA?ITA"},
  {"departamento"=>"Caquet?", "id"=>18460, "nombre"=>"MIL?N"},
  {"departamento"=>"Caquet?", "id"=>18479, "nombre"=>"MORELIA"},
  {"departamento"=>"Caquet?", "id"=>18592, "nombre"=>"PUERTO RICO"},
  {"departamento"=>"Caquet?", "id"=>18610, "nombre"=>"SAN JOS? DEL FRAGUA"},
  {"departamento"=>"Caquet?", "id"=>18753, "nombre"=>"SAN VICENTE DEL CAGU?N"},
  {"departamento"=>"Caquet?", "id"=>18756, "nombre"=>"SOLANO"},
  {"departamento"=>"Caquet?", "id"=>18785, "nombre"=>"SOLITA"},
  {"departamento"=>"Caquet?", "id"=>18860, "nombre"=>"VALPARA?SO"},
  {"departamento"=>"Cauca", "id"=>19001, "nombre"=>"POPAY?N"},
  {"departamento"=>"Cauca", "id"=>19022, "nombre"=>"ALMAGUER"},
  {"departamento"=>"Cauca", "id"=>19050, "nombre"=>"ARGELIA"},
  {"departamento"=>"Cauca", "id"=>19075, "nombre"=>"BALBOA"},
  {"departamento"=>"Cauca", "id"=>19100, "nombre"=>"BOLIVAR"},
  {"departamento"=>"Cauca", "id"=>19110, "nombre"=>"BUENOS AIRES"},
  {"departamento"=>"Cauca", "id"=>19130, "nombre"=>"CAJIB?O"},
  {"departamento"=>"Cauca", "id"=>19137, "nombre"=>"CALDONO"},
  {"departamento"=>"Cauca", "id"=>19142, "nombre"=>"CALOTO"},
  {"departamento"=>"Cauca", "id"=>19212, "nombre"=>"CORINTO"},
  {"departamento"=>"Cauca", "id"=>19256, "nombre"=>"EL TAMBO"},
  {"departamento"=>"Cauca", "id"=>19290, "nombre"=>"FLORENCIA"},
  {"departamento"=>"Cauca", "id"=>19318, "nombre"=>"GUAPI"},
  {"departamento"=>"Cauca", "id"=>19355, "nombre"=>"INZ?"},
  {"departamento"=>"Cauca", "id"=>19364, "nombre"=>"JAMBAL"},
  {"departamento"=>"Cauca", "id"=>19392, "nombre"=>"LA SIERRA"},
  {"departamento"=>"Cauca", "id"=>19397, "nombre"=>"LA VEGA"},
  {"departamento"=>"Cauca", "id"=>19418, "nombre"=>"L?PEZ"},
  {"departamento"=>"Cauca", "id"=>19450, "nombre"=>"MERCADERES"},
  {"departamento"=>"Cauca", "id"=>19455, "nombre"=>"MIRANDA"},
  {"departamento"=>"Cauca", "id"=>19473, "nombre"=>"MORALES"},
  {"departamento"=>"Cauca", "id"=>19513, "nombre"=>"PADILLA"},
  {"departamento"=>"Cauca", "id"=>19517, "nombre"=>"PAEZ"},
  {"departamento"=>"Cauca", "id"=>19532, "nombre"=>"PAT?A"},
  {"departamento"=>"Cauca", "id"=>19533, "nombre"=>"PIAMONTE"},
  {"departamento"=>"Cauca", "id"=>19548, "nombre"=>"PIENDAM"},
  {"departamento"=>"Cauca", "id"=>19573, "nombre"=>"PUERTO TEJADA"},
  {"departamento"=>"Cauca", "id"=>19585, "nombre"=>"PURAC?"},
  {"departamento"=>"Cauca", "id"=>19622, "nombre"=>"ROSAS"},
  {"departamento"=>"Cauca", "id"=>19693, "nombre"=>"SAN SEBASTI?N"},
  {"departamento"=>"Cauca", "id"=>19698, "nombre"=>"SANTANDER DE QUILICHAO"},
  {"departamento"=>"Cauca", "id"=>19701, "nombre"=>"SANTA ROSA"},
  {"departamento"=>"Cauca", "id"=>19743, "nombre"=>"SILVIA"},
  {"departamento"=>"Cauca", "id"=>19760, "nombre"=>"SOTARA"},
  {"departamento"=>"Cauca", "id"=>19780, "nombre"=>"SU?REZ"},
  {"departamento"=>"Cauca", "id"=>19785, "nombre"=>"SUCRE"},
  {"departamento"=>"Cauca", "id"=>19807, "nombre"=>"TIMB?O"},
  {"departamento"=>"Cauca", "id"=>19809, "nombre"=>"TIMBIQU"},
  {"departamento"=>"Cauca", "id"=>19821, "nombre"=>"TORIBIO"},
  {"departamento"=>"Cauca", "id"=>19824, "nombre"=>"TOTOR"},
  {"departamento"=>"Cauca", "id"=>19845, "nombre"=>"VILLA RICA"},
  {"departamento"=>"Cesar", "id"=>20001, "nombre"=>"VALLEDUPAR"},
  {"departamento"=>"Cesar", "id"=>20011, "nombre"=>"AGUACHICA"},
  {"departamento"=>"Cesar", "id"=>20013, "nombre"=>"AGUST?N CODAZZI"},
  {"departamento"=>"Cesar", "id"=>20032, "nombre"=>"ASTREA"},
  {"departamento"=>"Cesar", "id"=>20045, "nombre"=>"BECERRIL"},
  {"departamento"=>"Cesar", "id"=>20060, "nombre"=>"BOSCONIA"},
  {"departamento"=>"Cesar", "id"=>20175, "nombre"=>"CHIMICHAGUA"},
  {"departamento"=>"Cesar", "id"=>20178, "nombre"=>"CHIRIGUAN?"},
  {"departamento"=>"Cesar", "id"=>20228, "nombre"=>"CURUMAN"},
  {"departamento"=>"Cesar", "id"=>20238, "nombre"=>"EL COPEY"},
  {"departamento"=>"Cesar", "id"=>20250, "nombre"=>"EL PASO"},
  {"departamento"=>"Cesar", "id"=>20295, "nombre"=>"GAMARRA"},
  {"departamento"=>"Cesar", "id"=>20310, "nombre"=>"GONZ?LEZ"},
  {"departamento"=>"Cesar", "id"=>20383, "nombre"=>"LA GLORIA"},
  {"departamento"=>"Cesar", "id"=>20400, "nombre"=>"LA JAGUA DE IBIRICO"},
  {"departamento"=>"Cesar", "id"=>20443, "nombre"=>"MANAURE"},
  {"departamento"=>"Cesar", "id"=>20517, "nombre"=>"PAILITAS"},
  {"departamento"=>"Cesar", "id"=>20550, "nombre"=>"PELAYA"},
  {"departamento"=>"Cesar", "id"=>20570, "nombre"=>"PUEBLO BELLO"},
  {"departamento"=>"Cesar", "id"=>20614, "nombre"=>"R?O DE ORO"},
  {"departamento"=>"Cesar", "id"=>20621, "nombre"=>"LA PAZ"},
  {"departamento"=>"Cesar", "id"=>20710, "nombre"=>"SAN ALBERTO"},
  {"departamento"=>"Cesar", "id"=>20750, "nombre"=>"SAN DIEGO"},
  {"departamento"=>"Cesar", "id"=>20770, "nombre"=>"SAN MART?N"},
  {"departamento"=>"Cesar", "id"=>20787, "nombre"=>"TAMALAMEQUE"},
  {"departamento"=>"C?rdoba", "id"=>23001, "nombre"=>"MONTER?A"},
  {"departamento"=>"C?rdoba", "id"=>23068, "nombre"=>"AYAPEL"},
  {"departamento"=>"C?rdoba", "id"=>23079, "nombre"=>"BUENAVISTA"},
  {"departamento"=>"C?rdoba", "id"=>23090, "nombre"=>"CANALETE"},
  {"departamento"=>"C?rdoba", "id"=>23162, "nombre"=>"CERET?"},
  {"departamento"=>"C?rdoba", "id"=>23168, "nombre"=>"CHIM?"},
  {"departamento"=>"C?rdoba", "id"=>23182, "nombre"=>"CHIN"},
  {"departamento"=>"C?rdoba", "id"=>23189, "nombre"=>"CI?NAGA DE ORO"},
  {"departamento"=>"C?rdoba", "id"=>23300, "nombre"=>"COTORRA"},
  {"departamento"=>"C?rdoba", "id"=>23350, "nombre"=>"LA APARTADA"},
  {"departamento"=>"C?rdoba", "id"=>23417, "nombre"=>"LORICA"},
  {"departamento"=>"C?rdoba", "id"=>23419, "nombre"=>"LOS C?RDOBAS"},
  {"departamento"=>"C?rdoba", "id"=>23464, "nombre"=>"MOMIL"},
  {"departamento"=>"C?rdoba", "id"=>23466, "nombre"=>"MONTEL?BANO"},
  {"departamento"=>"C?rdoba", "id"=>23500, "nombre"=>"MO?ITOS"},
  {"departamento"=>"C?rdoba", "id"=>23555, "nombre"=>"PLANETA RICA"},
  {"departamento"=>"C?rdoba", "id"=>23570, "nombre"=>"PUEBLO NUEVO"},
  {"departamento"=>"C?rdoba", "id"=>23574, "nombre"=>"PUERTO ESCONDIDO"},
  {"departamento"=>"C?rdoba", "id"=>23580, "nombre"=>"PUERTO LIBERTADOR"},
  {"departamento"=>"C?rdoba", "id"=>23586, "nombre"=>"PUR?SIMA"},
  {"departamento"=>"C?rdoba", "id"=>23660, "nombre"=>"SAHAG"},
  {"departamento"=>"C?rdoba", "id"=>23670, "nombre"=>"SAN ANDR?S SOTAVENTO"},
  {"departamento"=>"C?rdoba", "id"=>23672, "nombre"=>"SAN ANTERO"},
  {"departamento"=>"C?rdoba", "id"=>23675, "nombre"=>"SAN BERNARDO DEL VIENTO"},
  {"departamento"=>"C?rdoba", "id"=>23678, "nombre"=>"SAN CARLOS"},
  {"departamento"=>"C?rdoba", "id"=>23686, "nombre"=>"SAN PELAYO"},
  {"departamento"=>"C?rdoba", "id"=>23807, "nombre"=>"TIERRALTA"},
  {"departamento"=>"C?rdoba", "id"=>23855, "nombre"=>"VALENCIA"},
  {"departamento"=>"Cundinamarca", "id"=>25001, "nombre"=>"AGUA DE DIOS"},
  {"departamento"=>"Cundinamarca", "id"=>25019, "nombre"=>"ALB?N"},
  {"departamento"=>"Cundinamarca", "id"=>25035, "nombre"=>"ANAPOIMA"},
  {"departamento"=>"Cundinamarca", "id"=>25040, "nombre"=>"ANOLAIMA"},
  {"departamento"=>"Cundinamarca", "id"=>25053, "nombre"=>"ARBEL?EZ"},
  {"departamento"=>"Cundinamarca", "id"=>25086, "nombre"=>"BELTR?N"},
  {"departamento"=>"Cundinamarca", "id"=>25095, "nombre"=>"BITUIMA"},
  {"departamento"=>"Cundinamarca", "id"=>25099, "nombre"=>"BOJAC?"},
  {"departamento"=>"Cundinamarca", "id"=>25120, "nombre"=>"CABRERA"},
  {"departamento"=>"Cundinamarca", "id"=>25123, "nombre"=>"CACHIPAY"},
  {"departamento"=>"Cundinamarca", "id"=>25126, "nombre"=>"CAJIC?"},
  {"departamento"=>"Cundinamarca", "id"=>25148, "nombre"=>"CAPARRAP"},
  {"departamento"=>"Cundinamarca", "id"=>25151, "nombre"=>"CAQUEZA"},
  {"departamento"=>"Cundinamarca", "id"=>25154, "nombre"=>"CARMEN DE CARUPA"},
  {"departamento"=>"Cundinamarca", "id"=>25168, "nombre"=>"CHAGUAN"},
  {"departamento"=>"Cundinamarca", "id"=>25175, "nombre"=>"CH?A"},
  {"departamento"=>"Cundinamarca", "id"=>25178, "nombre"=>"CHIPAQUE"},
  {"departamento"=>"Cundinamarca", "id"=>25181, "nombre"=>"CHOACH"},
  {"departamento"=>"Cundinamarca", "id"=>25183, "nombre"=>"CHOCONT?"},
  {"departamento"=>"Cundinamarca", "id"=>25200, "nombre"=>"COGUA"},
  {"departamento"=>"Cundinamarca", "id"=>25214, "nombre"=>"COTA"},
  {"departamento"=>"Cundinamarca", "id"=>25224, "nombre"=>"CUCUNUB?"},
  {"departamento"=>"Cundinamarca", "id"=>25245, "nombre"=>"EL COLEGIO"},
  {"departamento"=>"Cundinamarca", "id"=>25258, "nombre"=>"EL PE?"},
  {"departamento"=>"Cundinamarca", "id"=>25260, "nombre"=>"EL ROSAL"},
  {"departamento"=>"Cundinamarca", "id"=>25269, "nombre"=>"FACATATIV?"},
  {"departamento"=>"Cundinamarca", "id"=>25279, "nombre"=>"FOMEQUE"},
  {"departamento"=>"Cundinamarca", "id"=>25281, "nombre"=>"FOSCA"},
  {"departamento"=>"Cundinamarca", "id"=>25286, "nombre"=>"FUNZA"},
  {"departamento"=>"Cundinamarca", "id"=>25288, "nombre"=>"F?QUENE"},
  {"departamento"=>"Cundinamarca", "id"=>25290, "nombre"=>"FUSAGASUG?"},
  {"departamento"=>"Cundinamarca", "id"=>25293, "nombre"=>"GACHALA"},
  {"departamento"=>"Cundinamarca", "id"=>25295, "nombre"=>"GACHANCIP?"},
  {"departamento"=>"Cundinamarca", "id"=>25297, "nombre"=>"GACHET?"},
  {"departamento"=>"Cundinamarca", "id"=>25299, "nombre"=>"GAMA"},
  {"departamento"=>"Cundinamarca", "id"=>25307, "nombre"=>"GIRARDOT"},
  {"departamento"=>"Cundinamarca", "id"=>25312, "nombre"=>"GRANADA"},
  {"departamento"=>"Cundinamarca", "id"=>25317, "nombre"=>"GUACHET?"},
  {"departamento"=>"Cundinamarca", "id"=>25320, "nombre"=>"GUADUAS"},
  {"departamento"=>"Cundinamarca", "id"=>25322, "nombre"=>"GUASCA"},
  {"departamento"=>"Cundinamarca", "id"=>25324, "nombre"=>"GUATAQU"},
  {"departamento"=>"Cundinamarca", "id"=>25326, "nombre"=>"GUATAVITA"},
  {"departamento"=>"Cundinamarca", "id"=>25328, "nombre"=>"GUAYABAL DE SIQUIMA"},
  {"departamento"=>"Cundinamarca", "id"=>25335, "nombre"=>"GUAYABETAL"},
  {"departamento"=>"Cundinamarca", "id"=>25339, "nombre"=>"GUTI?RREZ"},
  {"departamento"=>"Cundinamarca", "id"=>25368, "nombre"=>"JERUSAL?N"},
  {"departamento"=>"Cundinamarca", "id"=>25372, "nombre"=>"JUN?N"},
  {"departamento"=>"Cundinamarca", "id"=>25377, "nombre"=>"LA CALERA"},
  {"departamento"=>"Cundinamarca", "id"=>25386, "nombre"=>"LA MESA"},
  {"departamento"=>"Cundinamarca", "id"=>25394, "nombre"=>"LA PALMA"},
  {"departamento"=>"Cundinamarca", "id"=>25398, "nombre"=>"LA PE?A"},
  {"departamento"=>"Cundinamarca", "id"=>25402, "nombre"=>"LA VEGA"},
  {"departamento"=>"Cundinamarca", "id"=>25407, "nombre"=>"LENGUAZAQUE"},
  {"departamento"=>"Cundinamarca", "id"=>25426, "nombre"=>"MACHETA"},
  {"departamento"=>"Cundinamarca", "id"=>25430, "nombre"=>"MADRID"},
  {"departamento"=>"Cundinamarca", "id"=>25436, "nombre"=>"MANTA"},
  {"departamento"=>"Cundinamarca", "id"=>25438, "nombre"=>"MEDINA"},
  {"departamento"=>"Cundinamarca", "id"=>25473, "nombre"=>"MOSQUERA"},
  {"departamento"=>"Cundinamarca", "id"=>25483, "nombre"=>"NARI?O"},
  {"departamento"=>"Cundinamarca", "id"=>25486, "nombre"=>"NEMOC"},
  {"departamento"=>"Cundinamarca", "id"=>25488, "nombre"=>"NILO"},
  {"departamento"=>"Cundinamarca", "id"=>25489, "nombre"=>"NIMAIMA"},
  {"departamento"=>"Cundinamarca", "id"=>25491, "nombre"=>"NOCAIMA"},
  {"departamento"=>"Cundinamarca", "id"=>25506, "nombre"=>"VENECIA"},
  {"departamento"=>"Cundinamarca", "id"=>25513, "nombre"=>"PACHO"},
  {"departamento"=>"Cundinamarca", "id"=>25518, "nombre"=>"PAIME"},
  {"departamento"=>"Cundinamarca", "id"=>25524, "nombre"=>"PANDI"},
  {"departamento"=>"Cundinamarca", "id"=>25530, "nombre"=>"PARATEBUENO"},
  {"departamento"=>"Cundinamarca", "id"=>25535, "nombre"=>"PASCA"},
  {"departamento"=>"Cundinamarca", "id"=>25572, "nombre"=>"PUERTO SALGAR"},
  {"departamento"=>"Cundinamarca", "id"=>25580, "nombre"=>"PUL"},
  {"departamento"=>"Cundinamarca", "id"=>25592, "nombre"=>"QUEBRADANEGRA"},
  {"departamento"=>"Cundinamarca", "id"=>25594, "nombre"=>"QUETAME"},
  {"departamento"=>"Cundinamarca", "id"=>25596, "nombre"=>"QUIPILE"},
  {"departamento"=>"Cundinamarca", "id"=>25599, "nombre"=>"APULO"},
  {"departamento"=>"Cundinamarca", "id"=>25612, "nombre"=>"RICAURTE"},
  {"departamento"=>"Cundinamarca", "id"=>25645, "nombre"=>"SAN ANTONIO DEL TEQUENDAMA"},
  {"departamento"=>"Cundinamarca", "id"=>25649, "nombre"=>"SAN BERNARDO"},
  {"departamento"=>"Cundinamarca", "id"=>25653, "nombre"=>"SAN CAYETANO"},
  {"departamento"=>"Cundinamarca", "id"=>25658, "nombre"=>"SAN FRANCISCO"},
  {"departamento"=>"Cundinamarca", "id"=>25662, "nombre"=>"SAN JUAN DE R?O SECO"},
  {"departamento"=>"Cundinamarca", "id"=>25718, "nombre"=>"SASAIMA"},
  {"departamento"=>"Cundinamarca", "id"=>25736, "nombre"=>"SESQUIL?"},
  {"departamento"=>"Cundinamarca", "id"=>25740, "nombre"=>"SIBAT?"},
  {"departamento"=>"Cundinamarca", "id"=>25743, "nombre"=>"SILVANIA"},
  {"departamento"=>"Cundinamarca", "id"=>25745, "nombre"=>"SIMIJACA"},
  {"departamento"=>"Cundinamarca", "id"=>25754, "nombre"=>"SOACHA"},
  {"departamento"=>"Cundinamarca", "id"=>25758, "nombre"=>"SOP"},
  {"departamento"=>"Cundinamarca", "id"=>25769, "nombre"=>"SUBACHOQUE"},
  {"departamento"=>"Cundinamarca", "id"=>25772, "nombre"=>"SUESCA"},
  {"departamento"=>"Cundinamarca", "id"=>25777, "nombre"=>"SUPAT?"},
  {"departamento"=>"Cundinamarca", "id"=>25779, "nombre"=>"SUSA"},
  {"departamento"=>"Cundinamarca", "id"=>25781, "nombre"=>"SUTATAUSA"},
  {"departamento"=>"Cundinamarca", "id"=>25785, "nombre"=>"TABIO"},
  {"departamento"=>"Cundinamarca", "id"=>25793, "nombre"=>"TAUSA"},
  {"departamento"=>"Cundinamarca", "id"=>25797, "nombre"=>"TENA"},
  {"departamento"=>"Cundinamarca", "id"=>25799, "nombre"=>"TENJO"},
  {"departamento"=>"Cundinamarca", "id"=>25805, "nombre"=>"TIBACUY"},
  {"departamento"=>"Cundinamarca", "id"=>25807, "nombre"=>"TIBIRITA"},
  {"departamento"=>"Cundinamarca", "id"=>25815, "nombre"=>"TOCAIMA"},
  {"departamento"=>"Cundinamarca", "id"=>25817, "nombre"=>"TOCANCIP?"},
  {"departamento"=>"Cundinamarca", "id"=>25823, "nombre"=>"TOPAIP"},
  {"departamento"=>"Cundinamarca", "id"=>25839, "nombre"=>"UBAL?"},
  {"departamento"=>"Cundinamarca", "id"=>25841, "nombre"=>"UBAQUE"},
  {"departamento"=>"Cundinamarca", "id"=>25843, "nombre"=>"VILLA DE SAN DIEGO DE UBATE"},
  {"departamento"=>"Cundinamarca", "id"=>25845, "nombre"=>"UNE"},
  {"departamento"=>"Cundinamarca", "id"=>25851, "nombre"=>"?TICA"},
  {"departamento"=>"Cundinamarca", "id"=>25862, "nombre"=>"VERGARA"},
  {"departamento"=>"Cundinamarca", "id"=>25867, "nombre"=>"VIAN"},
  {"departamento"=>"Cundinamarca", "id"=>25871, "nombre"=>"VILLAG?MEZ"},
  {"departamento"=>"Cundinamarca", "id"=>25873, "nombre"=>"VILLAPINZ"},
  {"departamento"=>"Cundinamarca", "id"=>25875, "nombre"=>"VILLETA"},
  {"departamento"=>"Cundinamarca", "id"=>25878, "nombre"=>"VIOT?"},
  {"departamento"=>"Cundinamarca", "id"=>25885, "nombre"=>"YACOP"},
  {"departamento"=>"Cundinamarca", "id"=>25898, "nombre"=>"ZIPAC"},
  {"departamento"=>"Cundinamarca", "id"=>25899, "nombre"=>"ZIPAQUIR?"},
  {"departamento"=>"Choco", "id"=>27001, "nombre"=>"QUIBD0"},
  {"departamento"=>"Choco", "id"=>27006, "nombre"=>"ACAND"},
  {"departamento"=>"Choco", "id"=>27025, "nombre"=>"ALTO BAUDO"},
  {"departamento"=>"Choco", "id"=>27050, "nombre"=>"ATRATO"},
  {"departamento"=>"Choco", "id"=>27073, "nombre"=>"BAGAD"},
  {"departamento"=>"Choco", "id"=>27075, "nombre"=>"BAH?A SOLANO"},
  {"departamento"=>"Choco", "id"=>27077, "nombre"=>"BAJO BAUD"},
  {"departamento"=>"Choco", "id"=>27086, "nombre"=>"BEL?N DE BAJIR?"},
  {"departamento"=>"Choco", "id"=>27099, "nombre"=>"BOJAYA"},
  {"departamento"=>"Choco", "id"=>27135, "nombre"=>"EL CANT?N DEL SAN PABLO"},
  {"departamento"=>"Choco", "id"=>27150, "nombre"=>"CARMEN DEL DARIEN"},
  {"departamento"=>"Choco", "id"=>27160, "nombre"=>"C?RTEGUI"},
  {"departamento"=>"Choco", "id"=>27205, "nombre"=>"CONDOTO"},
  {"departamento"=>"Choco", "id"=>27245, "nombre"=>"EL CARMEN DE ATRATO"},
  {"departamento"=>"Choco", "id"=>27250, "nombre"=>"EL LITORAL DEL SAN JUAN"},
  {"departamento"=>"Choco", "id"=>27361, "nombre"=>"ISTMINA"},
  {"departamento"=>"Choco", "id"=>27372, "nombre"=>"JURAD"},
  {"departamento"=>"Choco", "id"=>27413, "nombre"=>"LLOR"},
  {"departamento"=>"Choco", "id"=>27425, "nombre"=>"MEDIO ATRATO"},
  {"departamento"=>"Choco", "id"=>27430, "nombre"=>"MEDIO BAUD"},
  {"departamento"=>"Choco", "id"=>27450, "nombre"=>"MEDIO SAN JUAN"},
  {"departamento"=>"Choco", "id"=>27491, "nombre"=>"N?VITA"},
  {"departamento"=>"Choco", "id"=>27495, "nombre"=>"NUQU"},
  {"departamento"=>"Choco", "id"=>27580, "nombre"=>"R?O IRO"},
  {"departamento"=>"Choco", "id"=>27600, "nombre"=>"R?O QUITO"},
  {"departamento"=>"Choco", "id"=>27615, "nombre"=>"RIOSUCIO"},
  {"departamento"=>"Choco", "id"=>27660, "nombre"=>"SAN JOS? DEL PALMAR"},
  {"departamento"=>"Choco", "id"=>27745, "nombre"=>"SIP"},
  {"departamento"=>"Choco", "id"=>27787, "nombre"=>"TAD"},
  {"departamento"=>"Choco", "id"=>27800, "nombre"=>"UNGU?A"},
  {"departamento"=>"Choco", "id"=>27810, "nombre"=>"UNI?N PANAMERICANA"},
  {"departamento"=>"Huila", "id"=>41001, "nombre"=>"NEIVA"},
  {"departamento"=>"Huila", "id"=>41006, "nombre"=>"ACEVEDO"},
  {"departamento"=>"Huila", "id"=>41013, "nombre"=>"AGRADO"},
  {"departamento"=>"Huila", "id"=>41016, "nombre"=>"AIPE"},
  {"departamento"=>"Huila", "id"=>41020, "nombre"=>"ALGECIRAS"},
  {"departamento"=>"Huila", "id"=>41026, "nombre"=>"ALTAMIRA"},
  {"departamento"=>"Huila", "id"=>41078, "nombre"=>"BARAYA"},
  {"departamento"=>"Huila", "id"=>41132, "nombre"=>"CAMPOALEGRE"},
  {"departamento"=>"Huila", "id"=>41206, "nombre"=>"COLOMBIA"},
  {"departamento"=>"Huila", "id"=>41244, "nombre"=>"EL?AS"},
  {"departamento"=>"Huila", "id"=>41298, "nombre"=>"GARZ"},
  {"departamento"=>"Huila", "id"=>41306, "nombre"=>"GIGANTE"},
  {"departamento"=>"Huila", "id"=>41319, "nombre"=>"GUADALUPE"},
  {"departamento"=>"Huila", "id"=>41349, "nombre"=>"HOBO"},
  {"departamento"=>"Huila", "id"=>41357, "nombre"=>"IQUIRA"},
  {"departamento"=>"Huila", "id"=>41359, "nombre"=>"ISNOS"},
  {"departamento"=>"Huila", "id"=>41378, "nombre"=>"LA ARGENTINA"},
  {"departamento"=>"Huila", "id"=>41396, "nombre"=>"LA PLATA"},
  {"departamento"=>"Huila", "id"=>41483, "nombre"=>"N?TAGA"},
  {"departamento"=>"Huila", "id"=>41503, "nombre"=>"OPORAPA"},
  {"departamento"=>"Huila", "id"=>41518, "nombre"=>"PAICOL"},
  {"departamento"=>"Huila", "id"=>41524, "nombre"=>"PALERMO"},
  {"departamento"=>"Huila", "id"=>41530, "nombre"=>"PALESTINA"},
  {"departamento"=>"Huila", "id"=>41548, "nombre"=>"PITAL"},
  {"departamento"=>"Huila", "id"=>41551, "nombre"=>"PITALITO"},
  {"departamento"=>"Huila", "id"=>41615, "nombre"=>"RIVERA"},
  {"departamento"=>"Huila", "id"=>41660, "nombre"=>"SALADOBLANCO"},
  {"departamento"=>"Huila", "id"=>41668, "nombre"=>"SAN AGUST?N"},
  {"departamento"=>"Huila", "id"=>41676, "nombre"=>"SANTA MAR?A"},
  {"departamento"=>"Huila", "id"=>41770, "nombre"=>"SUAZA"},
  {"departamento"=>"Huila", "id"=>41791, "nombre"=>"TARQUI"},
  {"departamento"=>"Huila", "id"=>41797, "nombre"=>"TESALIA"},
  {"departamento"=>"Huila", "id"=>41799, "nombre"=>"TELLO"},
  {"departamento"=>"Huila", "id"=>41801, "nombre"=>"TERUEL"},
  {"departamento"=>"Huila", "id"=>41807, "nombre"=>"TIMAN?"},
  {"departamento"=>"Huila", "id"=>41872, "nombre"=>"VILLAVIEJA"},
  {"departamento"=>"Huila", "id"=>41885, "nombre"=>"YAGUAR?"},
  {"departamento"=>"La Guajira", "id"=>44001, "nombre"=>"RIOHACHA"},
  {"departamento"=>"La Guajira", "id"=>44035, "nombre"=>"ALBANIA"},
  {"departamento"=>"La Guajira", "id"=>44078, "nombre"=>"BARRANCAS"},
  {"departamento"=>"La Guajira", "id"=>44090, "nombre"=>"DIBULLA"},
  {"departamento"=>"La Guajira", "id"=>44098, "nombre"=>"DISTRACCI"},
  {"departamento"=>"La Guajira", "id"=>44110, "nombre"=>"EL MOLINO"},
  {"departamento"=>"La Guajira", "id"=>44279, "nombre"=>"FONSECA"},
  {"departamento"=>"La Guajira", "id"=>44378, "nombre"=>"HATONUEVO"},
  {"departamento"=>"La Guajira", "id"=>44420, "nombre"=>"LA JAGUA DEL PILAR"},
  {"departamento"=>"La Guajira", "id"=>44430, "nombre"=>"MAICAO"},
  {"departamento"=>"La Guajira", "id"=>44560, "nombre"=>"MANAURE"},
  {"departamento"=>"La Guajira", "id"=>44650, "nombre"=>"SAN JUAN DEL CESAR"},
  {"departamento"=>"La Guajira", "id"=>44847, "nombre"=>"URIBIA"},
  {"departamento"=>"La Guajira", "id"=>44855, "nombre"=>"URUMITA"},
  {"departamento"=>"La Guajira", "id"=>44874, "nombre"=>"VILLANUEVA"},
  {"departamento"=>"Magdalena", "id"=>47001, "nombre"=>"SANTA MARTA"},
  {"departamento"=>"Magdalena", "id"=>47030, "nombre"=>"ALGARROBO"},
  {"departamento"=>"Magdalena", "id"=>47053, "nombre"=>"ARACATACA"},
  {"departamento"=>"Magdalena", "id"=>47058, "nombre"=>"ARIGUAN"},
  {"departamento"=>"Magdalena", "id"=>47161, "nombre"=>"CERRO SAN ANTONIO"},
  {"departamento"=>"Magdalena", "id"=>47170, "nombre"=>"CHIBOLO"},
  {"departamento"=>"Magdalena", "id"=>47189, "nombre"=>"CI?NAGA"},
  {"departamento"=>"Magdalena", "id"=>47205, "nombre"=>"CONCORDIA"},
  {"departamento"=>"Magdalena", "id"=>47245, "nombre"=>"EL BANCO"},
  {"departamento"=>"Magdalena", "id"=>47258, "nombre"=>"EL PI?ON"},
  {"departamento"=>"Magdalena", "id"=>47268, "nombre"=>"EL RET?N"},
  {"departamento"=>"Magdalena", "id"=>47288, "nombre"=>"FUNDACI"},
  {"departamento"=>"Magdalena", "id"=>47318, "nombre"=>"GUAMAL"},
  {"departamento"=>"Magdalena", "id"=>47460, "nombre"=>"NUEVA GRANADA"},
  {"departamento"=>"Magdalena", "id"=>47541, "nombre"=>"PEDRAZA"},
  {"departamento"=>"Magdalena", "id"=>47545, "nombre"=>"PIJI?O DEL CARMEN"},
  {"departamento"=>"Magdalena", "id"=>47551, "nombre"=>"PIVIJAY"},
  {"departamento"=>"Magdalena", "id"=>47555, "nombre"=>"PLATO"},
  {"departamento"=>"Magdalena", "id"=>47570, "nombre"=>"PUEBLOVIEJO"},
  {"departamento"=>"Magdalena", "id"=>47605, "nombre"=>"REMOLINO"},
  {"departamento"=>"Magdalena", "id"=>47660, "nombre"=>"SABANAS DE SAN ANGEL"},
  {"departamento"=>"Magdalena", "id"=>47675, "nombre"=>"SALAMINA"},
  {"departamento"=>"Magdalena", "id"=>47692, "nombre"=>"SAN SEBASTI?N DE BUENAVISTA"},
  {"departamento"=>"Magdalena", "id"=>47703, "nombre"=>"SAN ZEN"},
  {"departamento"=>"Magdalena", "id"=>47707, "nombre"=>"SANTA ANA"},
  {"departamento"=>"Magdalena", "id"=>47720, "nombre"=>"SANTA B?RBARA DE PINTO"},
  {"departamento"=>"Magdalena", "id"=>47745, "nombre"=>"SITIONUEVO"},
  {"departamento"=>"Magdalena", "id"=>47798, "nombre"=>"TENERIFE"},
  {"departamento"=>"Magdalena", "id"=>47960, "nombre"=>"ZAPAY?N"},
  {"departamento"=>"Magdalena", "id"=>47980, "nombre"=>"ZONA BANANERA"},
  {"departamento"=>"Meta", "id"=>50001, "nombre"=>"VILLAVICENCIO"},
  {"departamento"=>"Meta", "id"=>50006, "nombre"=>"ACACÍAS"},
  {"departamento"=>"Meta", "id"=>50110, "nombre"=>"BARRANCA DE UP?A"},
  {"departamento"=>"Meta", "id"=>50124, "nombre"=>"CABUYARO"},
  {"departamento"=>"Meta", "id"=>50150, "nombre"=>"CASTILLA LA NUEVA"},
  {"departamento"=>"Meta", "id"=>50223, "nombre"=>"CUBARRAL"},
  {"departamento"=>"Meta", "id"=>50226, "nombre"=>"CUMARAL"},
  {"departamento"=>"Meta", "id"=>50245, "nombre"=>"EL CALVARIO"},
  {"departamento"=>"Meta", "id"=>50251, "nombre"=>"EL CASTILLO"},
  {"departamento"=>"Meta", "id"=>50270, "nombre"=>"EL DORADO"},
  {"departamento"=>"Meta", "id"=>50287, "nombre"=>"FUENTE DE ORO"},
  {"departamento"=>"Meta", "id"=>50313, "nombre"=>"GRANADA"},
  {"departamento"=>"Meta", "id"=>50318, "nombre"=>"GUAMAL"},
  {"departamento"=>"Meta", "id"=>50325, "nombre"=>"MAPIRIP?N"},
  {"departamento"=>"Meta", "id"=>50330, "nombre"=>"MESETAS"},
  {"departamento"=>"Meta", "id"=>50350, "nombre"=>"LA MACARENA"},
  {"departamento"=>"Meta", "id"=>50370, "nombre"=>"URIBE"},
  {"departamento"=>"Meta", "id"=>50400, "nombre"=>"LEJAN?AS"},
  {"departamento"=>"Meta", "id"=>50450, "nombre"=>"PUERTO CONCORDIA"},
  {"departamento"=>"Meta", "id"=>50568, "nombre"=>"PUERTO GAIT?N"},
  {"departamento"=>"Meta", "id"=>50573, "nombre"=>"PUERTO L?PEZ"},
  {"departamento"=>"Meta", "id"=>50577, "nombre"=>"PUERTO LLERAS"},
  {"departamento"=>"Meta", "id"=>50590, "nombre"=>"PUERTO RICO"},
  {"departamento"=>"Meta", "id"=>50606, "nombre"=>"RESTREPO"},
  {"departamento"=>"Meta", "id"=>50680, "nombre"=>"SAN CARLOS DE GUAROA"},
  {"departamento"=>"Meta", "id"=>50683, "nombre"=>"SAN JUAN DE ARAMA"},
  {"departamento"=>"Meta", "id"=>50686, "nombre"=>"SAN JUANITO"},
  {"departamento"=>"Meta", "id"=>50689, "nombre"=>"SAN MART?N"},
  {"departamento"=>"Meta", "id"=>50711, "nombre"=>"VISTAHERMOSA"},
  {"departamento"=>"Nari?o", "id"=>52001, "nombre"=>"PASTO"},
  {"departamento"=>"Nari?o", "id"=>52019, "nombre"=>"ALB?N"},
  {"departamento"=>"Nari?o", "id"=>52022, "nombre"=>"ALDANA"},
  {"departamento"=>"Nari?o", "id"=>52036, "nombre"=>"ANCUY?"},
  {"departamento"=>"Nari?o", "id"=>52051, "nombre"=>"ARBOLEDA"},
  {"departamento"=>"Nari?o", "id"=>52079, "nombre"=>"BARBACOAS"},
  {"departamento"=>"Nari?o", "id"=>52083, "nombre"=>"BEL?N"},
  {"departamento"=>"Nari?o", "id"=>52110, "nombre"=>"BUESACO"},
  {"departamento"=>"Nari?o", "id"=>52203, "nombre"=>"COL"},
  {"departamento"=>"Nari?o", "id"=>52207, "nombre"=>"CONSACA"},
  {"departamento"=>"Nari?o", "id"=>52210, "nombre"=>"CONTADERO"},
  {"departamento"=>"Nari?o", "id"=>52215, "nombre"=>"C?RDOBA"},
  {"departamento"=>"Nari?o", "id"=>52224, "nombre"=>"CUASPUD"},
  {"departamento"=>"Nari?o", "id"=>52227, "nombre"=>"CUMBAL"},
  {"departamento"=>"Nari?o", "id"=>52233, "nombre"=>"CUMBITARA"},
  {"departamento"=>"Nari?o", "id"=>52240, "nombre"=>"CHACHAG?"},
  {"departamento"=>"Nari?o", "id"=>52250, "nombre"=>"EL CHARCO"},
  {"departamento"=>"Nari?o", "id"=>52254, "nombre"=>"EL PE?OL"},
  {"departamento"=>"Nari?o", "id"=>52256, "nombre"=>"EL ROSARIO"},
  {"departamento"=>"Nari?o", "id"=>52258, "nombre"=>"EL TABL?N DE G?MEZ"},
  {"departamento"=>"Nari?o", "id"=>52260, "nombre"=>"EL TAMBO"},
  {"departamento"=>"Nari?o", "id"=>52287, "nombre"=>"FUNES"},
  {"departamento"=>"Nari?o", "id"=>52317, "nombre"=>"GUACHUCAL"},
  {"departamento"=>"Nari?o", "id"=>52320, "nombre"=>"GUAITARILLA"},
  {"departamento"=>"Nari?o", "id"=>52323, "nombre"=>"GUALMAT?N"},
  {"departamento"=>"Nari?o", "id"=>52352, "nombre"=>"ILES"},
  {"departamento"=>"Nari?o", "id"=>52354, "nombre"=>"IMU?S"},
  {"departamento"=>"Nari?o", "id"=>52356, "nombre"=>"IPIALES"},
  {"departamento"=>"Nari?o", "id"=>52378, "nombre"=>"LA CRUZ"},
  {"departamento"=>"Nari?o", "id"=>52381, "nombre"=>"LA FLORIDA"},
  {"departamento"=>"Nari?o", "id"=>52385, "nombre"=>"LA LLANADA"},
  {"departamento"=>"Nari?o", "id"=>52390, "nombre"=>"LA TOLA"},
  {"departamento"=>"Nari?o", "id"=>52399, "nombre"=>"LA UNI"},
  {"departamento"=>"Nari?o", "id"=>52405, "nombre"=>"LEIVA"},
  {"departamento"=>"Nari?o", "id"=>52411, "nombre"=>"LINARES"},
  {"departamento"=>"Nari?o", "id"=>52418, "nombre"=>"LOS ANDES"},
  {"departamento"=>"Nari?o", "id"=>52427, "nombre"=>"MAG?I"},
  {"departamento"=>"Nari?o", "id"=>52435, "nombre"=>"MALLAMA"},
  {"departamento"=>"Nari?o", "id"=>52473, "nombre"=>"MOSQUERA"},
  {"departamento"=>"Nari?o", "id"=>52480, "nombre"=>"NARI?O"},
  {"departamento"=>"Nari?o", "id"=>52490, "nombre"=>"OLAYA HERRERA"},
  {"departamento"=>"Nari?o", "id"=>52506, "nombre"=>"OSPINA"},
  {"departamento"=>"Nari?o", "id"=>52520, "nombre"=>"FRANCISCO PIZARRO"},
  {"departamento"=>"Nari?o", "id"=>52540, "nombre"=>"POLICARPA"},
  {"departamento"=>"Nari?o", "id"=>52560, "nombre"=>"POTOS"},
  {"departamento"=>"Nari?o", "id"=>52565, "nombre"=>"PROVIDENCIA"},
  {"departamento"=>"Nari?o", "id"=>52573, "nombre"=>"PUERRES"},
  {"departamento"=>"Nari?o", "id"=>52585, "nombre"=>"PUPIALES"},
  {"departamento"=>"Nari?o", "id"=>52612, "nombre"=>"RICAURTE"},
  {"departamento"=>"Nari?o", "id"=>52621, "nombre"=>"ROBERTO PAY?N"},
  {"departamento"=>"Nari?o", "id"=>52678, "nombre"=>"SAMANIEGO"},
  {"departamento"=>"Nari?o", "id"=>52683, "nombre"=>"SANDON?"},
  {"departamento"=>"Nari?o", "id"=>52685, "nombre"=>"SAN BERNARDO"},
  {"departamento"=>"Nari?o", "id"=>52687, "nombre"=>"SAN LORENZO"},
  {"departamento"=>"Nari?o", "id"=>52693, "nombre"=>"SAN PABLO"},
  {"departamento"=>"Nari?o", "id"=>52694, "nombre"=>"SAN PEDRO DE CARTAGO"},
  {"departamento"=>"Nari?o", "id"=>52696, "nombre"=>"SANTA B?RBARA"},
  {"departamento"=>"Nari?o", "id"=>52699, "nombre"=>"SANTACRUZ"},
  {"departamento"=>"Nari?o", "id"=>52720, "nombre"=>"SAPUYES"},
  {"departamento"=>"Nari?o", "id"=>52786, "nombre"=>"TAMINANGO"},
  {"departamento"=>"Nari?o", "id"=>52788, "nombre"=>"TANGUA"},
  {"departamento"=>"Nari?o", "id"=>52835, "nombre"=>"TUMACO"},
  {"departamento"=>"Nari?o", "id"=>52838, "nombre"=>"T?QUERRES"},
  {"departamento"=>"Nari?o", "id"=>52885, "nombre"=>"YACUANQUER"},
  {"departamento"=>"Norte de Santander", "id"=>54001, "nombre"=>"C?CUTA"},
  {"departamento"=>"Norte de Santander", "id"=>54003, "nombre"=>"ABREGO"},
  {"departamento"=>"Norte de Santander", "id"=>54051, "nombre"=>"ARBOLEDAS"},
  {"departamento"=>"Norte de Santander", "id"=>54099, "nombre"=>"BOCHALEMA"},
  {"departamento"=>"Norte de Santander", "id"=>54109, "nombre"=>"BUCARASICA"},
  {"departamento"=>"Norte de Santander", "id"=>54125, "nombre"=>"C?COTA"},
  {"departamento"=>"Norte de Santander", "id"=>54128, "nombre"=>"CACHIR?"},
  {"departamento"=>"Norte de Santander", "id"=>54172, "nombre"=>"CHIN?COTA"},
  {"departamento"=>"Norte de Santander", "id"=>54174, "nombre"=>"CHITAG?"},
  {"departamento"=>"Norte de Santander", "id"=>54206, "nombre"=>"CONVENCI"},
  {"departamento"=>"Norte de Santander", "id"=>54223, "nombre"=>"CUCUTILLA"},
  {"departamento"=>"Norte de Santander", "id"=>54239, "nombre"=>"DURANIA"},
  {"departamento"=>"Norte de Santander", "id"=>54245, "nombre"=>"EL CARMEN"},
  {"departamento"=>"Norte de Santander", "id"=>54250, "nombre"=>"EL TARRA"},
  {"departamento"=>"Norte de Santander", "id"=>54261, "nombre"=>"EL ZULIA"},
  {"departamento"=>"Norte de Santander", "id"=>54313, "nombre"=>"GRAMALOTE"},
  {"departamento"=>"Norte de Santander", "id"=>54344, "nombre"=>"HACAR"},
  {"departamento"=>"Norte de Santander", "id"=>54347, "nombre"=>"HERR?N"},
  {"departamento"=>"Norte de Santander", "id"=>54377, "nombre"=>"LABATECA"},
  {"departamento"=>"Norte de Santander", "id"=>54385, "nombre"=>"LA ESPERANZA"},
  {"departamento"=>"Norte de Santander", "id"=>54398, "nombre"=>"LA PLAYA"},
  {"departamento"=>"Norte de Santander", "id"=>54405, "nombre"=>"LOS PATIOS"},
  {"departamento"=>"Norte de Santander", "id"=>54418, "nombre"=>"LOURDES"},
  {"departamento"=>"Norte de Santander", "id"=>54480, "nombre"=>"MUTISCUA"},
  {"departamento"=>"Norte de Santander", "id"=>54498, "nombre"=>"OCA?A"},
  {"departamento"=>"Norte de Santander", "id"=>54518, "nombre"=>"PAMPLONA"},
  {"departamento"=>"Norte de Santander", "id"=>54520, "nombre"=>"PAMPLONITA"},
  {"departamento"=>"Norte de Santander", "id"=>54553, "nombre"=>"PUERTO SANTANDER"},
  {"departamento"=>"Norte de Santander", "id"=>54599, "nombre"=>"RAGONVALIA"},
  {"departamento"=>"Norte de Santander", "id"=>54660, "nombre"=>"SALAZAR"},
  {"departamento"=>"Norte de Santander", "id"=>54670, "nombre"=>"SAN CALIXTO"},
  {"departamento"=>"Norte de Santander", "id"=>54673, "nombre"=>"SAN CAYETANO"},
  {"departamento"=>"Norte de Santander", "id"=>54680, "nombre"=>"SANTIAGO"},
  {"departamento"=>"Norte de Santander", "id"=>54720, "nombre"=>"SARDINATA"},
  {"departamento"=>"Norte de Santander", "id"=>54743, "nombre"=>"SILOS"},
  {"departamento"=>"Norte de Santander", "id"=>54800, "nombre"=>"TEORAMA"},
  {"departamento"=>"Norte de Santander", "id"=>54810, "nombre"=>"TIB"},
  {"departamento"=>"Norte de Santander", "id"=>54820, "nombre"=>"TOLEDO"},
  {"departamento"=>"Norte de Santander", "id"=>54871, "nombre"=>"VILLA CARO"},
  {"departamento"=>"Norte de Santander", "id"=>54874, "nombre"=>"VILLA DEL ROSARIO"},
  {"departamento"=>"Quindio", "id"=>63001, "nombre"=>"ARMENIA"},
  {"departamento"=>"Quindio", "id"=>63111, "nombre"=>"BUENAVISTA"},
  {"departamento"=>"Quindio", "id"=>63130, "nombre"=>"CALARCA"},
  {"departamento"=>"Quindio", "id"=>63190, "nombre"=>"CIRCASIA"},
  {"departamento"=>"Quindio", "id"=>63212, "nombre"=>"C?RDOBA"},
  {"departamento"=>"Quindio", "id"=>63272, "nombre"=>"FILANDIA"},
  {"departamento"=>"Quindio", "id"=>63302, "nombre"=>"G?NOVA"},
  {"departamento"=>"Quindio", "id"=>63401, "nombre"=>"LA TEBAIDA"},
  {"departamento"=>"Quindio", "id"=>63470, "nombre"=>"MONTENEGRO"},
  {"departamento"=>"Quindio", "id"=>63548, "nombre"=>"PIJAO"},
  {"departamento"=>"Quindio", "id"=>63594, "nombre"=>"QUIMBAYA"},
  {"departamento"=>"Quindio", "id"=>63690, "nombre"=>"SALENTO"},
  {"departamento"=>"Risaralda", "id"=>66001, "nombre"=>"PEREIRA"},
  {"departamento"=>"Risaralda", "id"=>66045, "nombre"=>"AP?A"},
  {"departamento"=>"Risaralda", "id"=>66075, "nombre"=>"BALBOA"},
  {"departamento"=>"Risaralda", "id"=>66088, "nombre"=>"BEL?N DE UMBR?A"},
  {"departamento"=>"Risaralda", "id"=>66170, "nombre"=>"DOSQUEBRADAS"},
  {"departamento"=>"Risaralda", "id"=>66318, "nombre"=>"GU?TICA"},
  {"departamento"=>"Risaralda", "id"=>66383, "nombre"=>"LA CELIA"},
  {"departamento"=>"Risaralda", "id"=>66400, "nombre"=>"LA VIRGINIA"},
  {"departamento"=>"Risaralda", "id"=>66440, "nombre"=>"MARSELLA"},
  {"departamento"=>"Risaralda", "id"=>66456, "nombre"=>"MISTRAT"},
  {"departamento"=>"Risaralda", "id"=>66572, "nombre"=>"PUEBLO RICO"},
  {"departamento"=>"Risaralda", "id"=>66594, "nombre"=>"QUINCH?A"},
  {"departamento"=>"Risaralda", "id"=>66682, "nombre"=>"SANTA ROSA DE CABAL"},
  {"departamento"=>"Risaralda", "id"=>66687, "nombre"=>"SANTUARIO"},
  {"departamento"=>"Santander", "id"=>68001, "nombre"=>"BUCARAMANGA"},
  {"departamento"=>"Santander", "id"=>68013, "nombre"=>"AGUADA"},
  {"departamento"=>"Santander", "id"=>68020, "nombre"=>"ALBANIA"},
  {"departamento"=>"Santander", "id"=>68051, "nombre"=>"ARATOCA"},
  {"departamento"=>"Santander", "id"=>68077, "nombre"=>"BARBOSA"},
  {"departamento"=>"Santander", "id"=>68079, "nombre"=>"BARICHARA"},
  {"departamento"=>"Santander", "id"=>68081, "nombre"=>"BARRANCABERMEJA"},
  {"departamento"=>"Santander", "id"=>68092, "nombre"=>"BETULIA"},
  {"departamento"=>"Santander", "id"=>68101, "nombre"=>"BOLIVAR"},
  {"departamento"=>"Santander", "id"=>68121, "nombre"=>"CABRERA"},
  {"departamento"=>"Santander", "id"=>68132, "nombre"=>"CALIFORNIA"},
  {"departamento"=>"Santander", "id"=>68147, "nombre"=>"CAPITANEJO"},
  {"departamento"=>"Santander", "id"=>68152, "nombre"=>"CARCAS"},
  {"departamento"=>"Santander", "id"=>68160, "nombre"=>"CEPIT?"},
  {"departamento"=>"Santander", "id"=>68162, "nombre"=>"CERRITO"},
  {"departamento"=>"Santander", "id"=>68167, "nombre"=>"CHARAL?"},
  {"departamento"=>"Santander", "id"=>68169, "nombre"=>"CHARTA"},
  {"departamento"=>"Santander", "id"=>68176, "nombre"=>"CHIMA"},
  {"departamento"=>"Santander", "id"=>68179, "nombre"=>"CHIPAT?"},
  {"departamento"=>"Santander", "id"=>68190, "nombre"=>"CIMITARRA"},
  {"departamento"=>"Santander", "id"=>68207, "nombre"=>"CONCEPCI"},
  {"departamento"=>"Santander", "id"=>68209, "nombre"=>"CONFINES"},
  {"departamento"=>"Santander", "id"=>68211, "nombre"=>"CONTRATACI"},
  {"departamento"=>"Santander", "id"=>68217, "nombre"=>"COROMORO"},
  {"departamento"=>"Santander", "id"=>68229, "nombre"=>"CURIT"},
  {"departamento"=>"Santander", "id"=>68235, "nombre"=>"EL CARMEN DE CHUCUR"},
  {"departamento"=>"Santander", "id"=>68245, "nombre"=>"EL GUACAMAYO"},
  {"departamento"=>"Santander", "id"=>68250, "nombre"=>"EL PE?"},
  {"departamento"=>"Santander", "id"=>68255, "nombre"=>"EL PLAY"},
  {"departamento"=>"Santander", "id"=>68264, "nombre"=>"ENCINO"},
  {"departamento"=>"Santander", "id"=>68266, "nombre"=>"ENCISO"},
  {"departamento"=>"Santander", "id"=>68271, "nombre"=>"FLORI?N"},
  {"departamento"=>"Santander", "id"=>68276, "nombre"=>"FLORIDABLANCA"},
  {"departamento"=>"Santander", "id"=>68296, "nombre"=>"GAL?N"},
  {"departamento"=>"Santander", "id"=>68298, "nombre"=>"GAMBITA"},
  {"departamento"=>"Santander", "id"=>68307, "nombre"=>"GIR"},
  {"departamento"=>"Santander", "id"=>68318, "nombre"=>"GUACA"},
  {"departamento"=>"Santander", "id"=>68320, "nombre"=>"GUADALUPE"},
  {"departamento"=>"Santander", "id"=>68322, "nombre"=>"GUAPOT?"},
  {"departamento"=>"Santander", "id"=>68324, "nombre"=>"GUAVAT?"},
  {"departamento"=>"Santander", "id"=>68327, "nombre"=>"G?EPSA"},
  {"departamento"=>"Santander", "id"=>68344, "nombre"=>"HATO"},
  {"departamento"=>"Santander", "id"=>68368, "nombre"=>"JES?S MAR?A"},
  {"departamento"=>"Santander", "id"=>68370, "nombre"=>"JORD?N"},
  {"departamento"=>"Santander", "id"=>68377, "nombre"=>"LA BELLEZA"},
  {"departamento"=>"Santander", "id"=>68385, "nombre"=>"LAND?ZURI"},
  {"departamento"=>"Santander", "id"=>68397, "nombre"=>"LA PAZ"},
  {"departamento"=>"Santander", "id"=>68406, "nombre"=>"LEBR?JA"},
  {"departamento"=>"Santander", "id"=>68418, "nombre"=>"LOS SANTOS"},
  {"departamento"=>"Santander", "id"=>68425, "nombre"=>"MACARAVITA"},
  {"departamento"=>"Santander", "id"=>68432, "nombre"=>"M?LAGA"},
  {"departamento"=>"Santander", "id"=>68444, "nombre"=>"MATANZA"},
  {"departamento"=>"Santander", "id"=>68464, "nombre"=>"MOGOTES"},
  {"departamento"=>"Santander", "id"=>68468, "nombre"=>"MOLAGAVITA"},
  {"departamento"=>"Santander", "id"=>68498, "nombre"=>"OCAMONTE"},
  {"departamento"=>"Santander", "id"=>68500, "nombre"=>"OIBA"},
  {"departamento"=>"Santander", "id"=>68502, "nombre"=>"ONZAGA"},
  {"departamento"=>"Santander", "id"=>68522, "nombre"=>"PALMAR"},
  {"departamento"=>"Santander", "id"=>68524, "nombre"=>"PALMAS DEL SOCORRO"},
  {"departamento"=>"Santander", "id"=>68533, "nombre"=>"P?RAMO"},
  {"departamento"=>"Santander", "id"=>68547, "nombre"=>"PIEDECUESTA"},
  {"departamento"=>"Santander", "id"=>68549, "nombre"=>"PINCHOTE"},
  {"departamento"=>"Santander", "id"=>68572, "nombre"=>"PUENTE NACIONAL"},
  {"departamento"=>"Santander", "id"=>68573, "nombre"=>"PUERTO PARRA"},
  {"departamento"=>"Santander", "id"=>68575, "nombre"=>"PUERTO WILCHES"},
  {"departamento"=>"Santander", "id"=>68615, "nombre"=>"RIONEGRO"},
  {"departamento"=>"Santander", "id"=>68655, "nombre"=>"SABANA DE TORRES"},
  {"departamento"=>"Santander", "id"=>68669, "nombre"=>"SAN ANDR?S"},
  {"departamento"=>"Santander", "id"=>68673, "nombre"=>"SAN BENITO"},
  {"departamento"=>"Santander", "id"=>68679, "nombre"=>"SAN GIL"},
  {"departamento"=>"Santander", "id"=>68682, "nombre"=>"SAN JOAQU?N"},
  {"departamento"=>"Santander", "id"=>68684, "nombre"=>"SAN JOS? DE MIRANDA"},
  {"departamento"=>"Santander", "id"=>68686, "nombre"=>"SAN MIGUEL"},
  {"departamento"=>"Santander", "id"=>68689, "nombre"=>"SAN VICENTE DE CHUCUR"},
  {"departamento"=>"Santander", "id"=>68705, "nombre"=>"SANTA B?RBARA"},
  {"departamento"=>"Santander", "id"=>68720, "nombre"=>"SANTA HELENA DEL OP"},
  {"departamento"=>"Santander", "id"=>68745, "nombre"=>"SIMACOTA"},
  {"departamento"=>"Santander", "id"=>68755, "nombre"=>"SOCORRO"},
  {"departamento"=>"Santander", "id"=>68770, "nombre"=>"SUAITA"},
  {"departamento"=>"Santander", "id"=>68773, "nombre"=>"SUCRE"},
  {"departamento"=>"Santander", "id"=>68780, "nombre"=>"SURAT?"},
  {"departamento"=>"Santander", "id"=>68820, "nombre"=>"TONA"},
  {"departamento"=>"Santander", "id"=>68855, "nombre"=>"VALLE DE SAN JOS?"},
  {"departamento"=>"Santander", "id"=>68861, "nombre"=>"V?LEZ"},
  {"departamento"=>"Santander", "id"=>68867, "nombre"=>"VETAS"},
  {"departamento"=>"Santander", "id"=>68872, "nombre"=>"VILLANUEVA"},
  {"departamento"=>"Santander", "id"=>68895, "nombre"=>"ZAPATOCA"},
  {"departamento"=>"Sucre", "id"=>70001, "nombre"=>"SINCELEJO"},
  {"departamento"=>"Sucre", "id"=>70110, "nombre"=>"BUENAVISTA"},
  {"departamento"=>"Sucre", "id"=>70124, "nombre"=>"CAIMITO"},
  {"departamento"=>"Sucre", "id"=>70204, "nombre"=>"COLOSO"},
  {"departamento"=>"Sucre", "id"=>70215, "nombre"=>"COROZAL"},
  {"departamento"=>"Sucre", "id"=>70221, "nombre"=>"COVE?AS"},
  {"departamento"=>"Sucre", "id"=>70230, "nombre"=>"CHAL?N"},
  {"departamento"=>"Sucre", "id"=>70233, "nombre"=>"EL ROBLE"},
  {"departamento"=>"Sucre", "id"=>70235, "nombre"=>"GALERAS"},
  {"departamento"=>"Sucre", "id"=>70265, "nombre"=>"GUARANDA"},
  {"departamento"=>"Sucre", "id"=>70400, "nombre"=>"LA UNI"},
  {"departamento"=>"Sucre", "id"=>70418, "nombre"=>"LOS PALMITOS"},
  {"departamento"=>"Sucre", "id"=>70429, "nombre"=>"MAJAGUAL"},
  {"departamento"=>"Sucre", "id"=>70473, "nombre"=>"MORROA"},
  {"departamento"=>"Sucre", "id"=>70508, "nombre"=>"OVEJAS"},
  {"departamento"=>"Sucre", "id"=>70523, "nombre"=>"PALMITO"},
  {"departamento"=>"Sucre", "id"=>70670, "nombre"=>"SAMPU?S"},
  {"departamento"=>"Sucre", "id"=>70678, "nombre"=>"SAN BENITO ABAD"},
  {"departamento"=>"Sucre", "id"=>70702, "nombre"=>"SAN JUAN DE BETULIA"},
  {"departamento"=>"Sucre", "id"=>70708, "nombre"=>"SAN MARCOS"},
  {"departamento"=>"Sucre", "id"=>70713, "nombre"=>"SAN ONOFRE"},
  {"departamento"=>"Sucre", "id"=>70717, "nombre"=>"SAN PEDRO"},
  {"departamento"=>"Sucre", "id"=>70742, "nombre"=>"SINC?"},
  {"departamento"=>"Sucre", "id"=>70771, "nombre"=>"SUCRE"},
  {"departamento"=>"Sucre", "id"=>70820, "nombre"=>"SANTIAGO DE TOL"},
  {"departamento"=>"Sucre", "id"=>70823, "nombre"=>"TOL? VIEJO"},
  {"departamento"=>"Tolima", "id"=>73001, "nombre"=>"IBAGU?"},
  {"departamento"=>"Tolima", "id"=>73024, "nombre"=>"ALPUJARRA"},
  {"departamento"=>"Tolima", "id"=>73026, "nombre"=>"ALVARADO"},
  {"departamento"=>"Tolima", "id"=>73030, "nombre"=>"AMBALEMA"},
  {"departamento"=>"Tolima", "id"=>73043, "nombre"=>"ANZO?TEGUI"},
  {"departamento"=>"Tolima", "id"=>73055, "nombre"=>"ARMERO"},
  {"departamento"=>"Tolima", "id"=>73067, "nombre"=>"ATACO"},
  {"departamento"=>"Tolima", "id"=>73124, "nombre"=>"CAJAMARCA"},
  {"departamento"=>"Tolima", "id"=>73148, "nombre"=>"CARMEN DE APICAL?"},
  {"departamento"=>"Tolima", "id"=>73152, "nombre"=>"CASABIANCA"},
  {"departamento"=>"Tolima", "id"=>73168, "nombre"=>"CHAPARRAL"},
  {"departamento"=>"Tolima", "id"=>73200, "nombre"=>"COELLO"},
  {"departamento"=>"Tolima", "id"=>73217, "nombre"=>"COYAIMA"},
  {"departamento"=>"Tolima", "id"=>73226, "nombre"=>"CUNDAY"},
  {"departamento"=>"Tolima", "id"=>73236, "nombre"=>"DOLORES"},
  {"departamento"=>"Tolima", "id"=>73268, "nombre"=>"ESPINAL"},
  {"departamento"=>"Tolima", "id"=>73270, "nombre"=>"FALAN"},
  {"departamento"=>"Tolima", "id"=>73275, "nombre"=>"FLANDES"},
  {"departamento"=>"Tolima", "id"=>73283, "nombre"=>"FRESNO"},
  {"departamento"=>"Tolima", "id"=>73319, "nombre"=>"GUAMO"},
  {"departamento"=>"Tolima", "id"=>73347, "nombre"=>"HERVEO"},
  {"departamento"=>"Tolima", "id"=>73349, "nombre"=>"HONDA"},
  {"departamento"=>"Tolima", "id"=>73352, "nombre"=>"ICONONZO"},
  {"departamento"=>"Tolima", "id"=>73408, "nombre"=>"L?RIDA"},
  {"departamento"=>"Tolima", "id"=>73411, "nombre"=>"L?BANO"},
  {"departamento"=>"Tolima", "id"=>73443, "nombre"=>"MARIQUITA"},
  {"departamento"=>"Tolima", "id"=>73449, "nombre"=>"MELGAR"},
  {"departamento"=>"Tolima", "id"=>73461, "nombre"=>"MURILLO"},
  {"departamento"=>"Tolima", "id"=>73483, "nombre"=>"NATAGAIMA"},
  {"departamento"=>"Tolima", "id"=>73504, "nombre"=>"ORTEGA"},
  {"departamento"=>"Tolima", "id"=>73520, "nombre"=>"PALOCABILDO"},
  {"departamento"=>"Tolima", "id"=>73547, "nombre"=>"PIEDRAS"},
  {"departamento"=>"Tolima", "id"=>73555, "nombre"=>"PLANADAS"},
  {"departamento"=>"Tolima", "id"=>73563, "nombre"=>"PRADO"},
  {"departamento"=>"Tolima", "id"=>73585, "nombre"=>"PURIFICACI"},
  {"departamento"=>"Tolima", "id"=>73616, "nombre"=>"RIOBLANCO"},
  {"departamento"=>"Tolima", "id"=>73622, "nombre"=>"RONCESVALLES"},
  {"departamento"=>"Tolima", "id"=>73624, "nombre"=>"ROVIRA"},
  {"departamento"=>"Tolima", "id"=>73671, "nombre"=>"SALDA?A"},
  {"departamento"=>"Tolima", "id"=>73675, "nombre"=>"SAN ANTONIO"},
  {"departamento"=>"Tolima", "id"=>73678, "nombre"=>"SAN LUIS"},
  {"departamento"=>"Tolima", "id"=>73686, "nombre"=>"SANTA ISABEL"},
  {"departamento"=>"Tolima", "id"=>73770, "nombre"=>"SU?REZ"},
  {"departamento"=>"Tolima", "id"=>73854, "nombre"=>"VALLE DE SAN JUAN"},
  {"departamento"=>"Tolima", "id"=>73861, "nombre"=>"VENADILLO"},
  {"departamento"=>"Tolima", "id"=>73870, "nombre"=>"VILLAHERMOSA"},
  {"departamento"=>"Tolima", "id"=>73873, "nombre"=>"VILLARRICA"},
  {"departamento"=>"Valle del Cauca", "id"=>76001, "nombre"=>"CALI"},
  {"departamento"=>"Valle del Cauca", "id"=>76020, "nombre"=>"ALCAL?"},
  {"departamento"=>"Valle del Cauca", "id"=>76036, "nombre"=>"ANDALUC?A"},
  {"departamento"=>"Valle del Cauca", "id"=>76041, "nombre"=>"ANSERMANUEVO"},
  {"departamento"=>"Valle del Cauca", "id"=>76054, "nombre"=>"ARGELIA"},
  {"departamento"=>"Valle del Cauca", "id"=>76100, "nombre"=>"BOLIVAR"},
  {"departamento"=>"Valle del Cauca", "id"=>76109, "nombre"=>"BUENAVENTURA"},
  {"departamento"=>"Valle del Cauca", "id"=>76111, "nombre"=>"GUADALAJARA DE BUGA"},
  {"departamento"=>"Valle del Cauca", "id"=>76113, "nombre"=>"BUGALAGRANDE"},
  {"departamento"=>"Valle del Cauca", "id"=>76122, "nombre"=>"CAICEDONIA"},
  {"departamento"=>"Valle del Cauca", "id"=>76126, "nombre"=>"CALIMA"},
  {"departamento"=>"Valle del Cauca", "id"=>76130, "nombre"=>"CANDELARIA"},
  {"departamento"=>"Valle del Cauca", "id"=>76147, "nombre"=>"CARTAGO"},
  {"departamento"=>"Valle del Cauca", "id"=>76233, "nombre"=>"DAGUA"},
  {"departamento"=>"Valle del Cauca", "id"=>76243, "nombre"=>"EL ?GUILA"},
  {"departamento"=>"Valle del Cauca", "id"=>76246, "nombre"=>"EL CAIRO"},
  {"departamento"=>"Valle del Cauca", "id"=>76248, "nombre"=>"EL CERRITO"},
  {"departamento"=>"Valle del Cauca", "id"=>76250, "nombre"=>"EL DOVIO"},
  {"departamento"=>"Valle del Cauca", "id"=>76275, "nombre"=>"FLORIDA"},
  {"departamento"=>"Valle del Cauca", "id"=>76306, "nombre"=>"GINEBRA"},
  {"departamento"=>"Valle del Cauca", "id"=>76318, "nombre"=>"GUACAR"},
  {"departamento"=>"Valle del Cauca", "id"=>76364, "nombre"=>"JAMUND"},
  {"departamento"=>"Valle del Cauca", "id"=>76377, "nombre"=>"LA CUMBRE"},
  {"departamento"=>"Valle del Cauca", "id"=>76400, "nombre"=>"LA UNI"},
  {"departamento"=>"Valle del Cauca", "id"=>76403, "nombre"=>"LA VICTORIA"},
  {"departamento"=>"Valle del Cauca", "id"=>76497, "nombre"=>"OBANDO"},
  {"departamento"=>"Valle del Cauca", "id"=>76520, "nombre"=>"PALMIRA"},
  {"departamento"=>"Valle del Cauca", "id"=>76563, "nombre"=>"PRADERA"},
  {"departamento"=>"Valle del Cauca", "id"=>76606, "nombre"=>"RESTREPO"},
  {"departamento"=>"Valle del Cauca", "id"=>76616, "nombre"=>"RIOFR?O"},
  {"departamento"=>"Valle del Cauca", "id"=>76622, "nombre"=>"ROLDANILLO"},
  {"departamento"=>"Valle del Cauca", "id"=>76670, "nombre"=>"SAN PEDRO"},
  {"departamento"=>"Valle del Cauca", "id"=>76736, "nombre"=>"SEVILLA"},
  {"departamento"=>"Valle del Cauca", "id"=>76823, "nombre"=>"TORO"},
  {"departamento"=>"Valle del Cauca", "id"=>76828, "nombre"=>"TRUJILLO"},
  {"departamento"=>"Valle del Cauca", "id"=>76834, "nombre"=>"TULU?"},
  {"departamento"=>"Valle del Cauca", "id"=>76845, "nombre"=>"ULLOA"},
  {"departamento"=>"Valle del Cauca", "id"=>76863, "nombre"=>"VERSALLES"},
  {"departamento"=>"Valle del Cauca", "id"=>76869, "nombre"=>"VIJES"},
  {"departamento"=>"Valle del Cauca", "id"=>76890, "nombre"=>"YOTOCO"},
  {"departamento"=>"Valle del Cauca", "id"=>76892, "nombre"=>"YUMBO"},
  {"departamento"=>"Valle del Cauca", "id"=>76895, "nombre"=>"ZARZAL"},
  {"departamento"=>"Arauca", "id"=>81001, "nombre"=>"ARAUCA"},
  {"departamento"=>"Arauca", "id"=>81065, "nombre"=>"ARAUQUITA"},
  {"departamento"=>"Arauca", "id"=>81220, "nombre"=>"CRAVO NORTE"},
  {"departamento"=>"Arauca", "id"=>81300, "nombre"=>"FORTUL"},
  {"departamento"=>"Arauca", "id"=>81591, "nombre"=>"PUERTO ROND"},
  {"departamento"=>"Arauca", "id"=>81736, "nombre"=>"SARAVENA"},
  {"departamento"=>"Arauca", "id"=>81794, "nombre"=>"TAME"},
  {"departamento"=>"Casanare", "id"=>85001, "nombre"=>"YOPAL"},
  {"departamento"=>"Casanare", "id"=>85010, "nombre"=>"AGUAZUL"},
  {"departamento"=>"Casanare", "id"=>85015, "nombre"=>"CHAMEZA"},
  {"departamento"=>"Casanare", "id"=>85125, "nombre"=>"HATO COROZAL"},
  {"departamento"=>"Casanare", "id"=>85136, "nombre"=>"LA SALINA"},
  {"departamento"=>"Casanare", "id"=>85139, "nombre"=>"MAN"},
  {"departamento"=>"Casanare", "id"=>85162, "nombre"=>"MONTERREY"},
  {"departamento"=>"Casanare", "id"=>85225, "nombre"=>"NUNCH?A"},
  {"departamento"=>"Casanare", "id"=>85230, "nombre"=>"OROCU?"},
  {"departamento"=>"Casanare", "id"=>85250, "nombre"=>"PAZ DE ARIPORO"},
  {"departamento"=>"Casanare", "id"=>85263, "nombre"=>"PORE"},
  {"departamento"=>"Casanare", "id"=>85279, "nombre"=>"RECETOR"},
  {"departamento"=>"Casanare", "id"=>85300, "nombre"=>"SABANALARGA"},
  {"departamento"=>"Casanare", "id"=>85315, "nombre"=>"S?CAMA"},
  {"departamento"=>"Casanare", "id"=>85325, "nombre"=>"SAN LUIS DE PALENQUE"},
  {"departamento"=>"Casanare", "id"=>85400, "nombre"=>"T?MARA"},
  {"departamento"=>"Casanare", "id"=>85410, "nombre"=>"TAURAMENA"},
  {"departamento"=>"Casanare", "id"=>85430, "nombre"=>"TRINIDAD"},
  {"departamento"=>"Casanare", "id"=>85440, "nombre"=>"VILLANUEVA"},
  {"departamento"=>"Putumayo", "id"=>86001, "nombre"=>"MOCOA"},
  {"departamento"=>"Putumayo", "id"=>86219, "nombre"=>"COL"},
  {"departamento"=>"Putumayo", "id"=>86320, "nombre"=>"ORITO"},
  {"departamento"=>"Putumayo", "id"=>86568, "nombre"=>"PUERTO AS?S"},
  {"departamento"=>"Putumayo", "id"=>86569, "nombre"=>"PUERTO CAICEDO"},
  {"departamento"=>"Putumayo", "id"=>86571, "nombre"=>"PUERTO GUZM?N"},
  {"departamento"=>"Putumayo", "id"=>86573, "nombre"=>"LEGU?ZAMO"},
  {"departamento"=>"Putumayo", "id"=>86749, "nombre"=>"SIBUNDOY"},
  {"departamento"=>"Putumayo", "id"=>86755, "nombre"=>"SAN FRANCISCO"},
  {"departamento"=>"Putumayo", "id"=>86757, "nombre"=>"SAN MIGUEL"},
  {"departamento"=>"Putumayo", "id"=>86760, "nombre"=>"SANTIAGO"},
  {"departamento"=>"Putumayo", "id"=>86865, "nombre"=>"VALLE DEL GUAMUEZ"},
  {"departamento"=>"Putumayo", "id"=>86885, "nombre"=>"VILLAGARZ"},
  {"departamento"=>"Archipielago de San Andres, Providencia ", "id"=>88001, "nombre"=>"SAN ANDRES"},
  {"departamento"=>"Archipielago de San Andres, Providencia ", "id"=>88564, "nombre"=>"PROVIDENCIA"},
  {"departamento"=>"Amazonas", "id"=>91001, "nombre"=>"LETICIA"},
  {"departamento"=>"Amazonas", "id"=>91263, "nombre"=>"EL ENCANTO"},
  {"departamento"=>"Amazonas", "id"=>91405, "nombre"=>"LA CHORRERA"},
  {"departamento"=>"Amazonas", "id"=>91407, "nombre"=>"LA PEDRERA"},
  {"departamento"=>"Amazonas", "id"=>91430, "nombre"=>"LA VICTORIA"},
  {"departamento"=>"Amazonas", "id"=>91460, "nombre"=>"MIRITI - PARAN?"},
  {"departamento"=>"Amazonas", "id"=>91530, "nombre"=>"PUERTO ALEGR?A"},
  {"departamento"=>"Amazonas", "id"=>91536, "nombre"=>"PUERTO ARICA"},
  {"departamento"=>"Amazonas", "id"=>91540, "nombre"=>"PUERTO NARI?O"},
  {"departamento"=>"Amazonas", "id"=>91669, "nombre"=>"PUERTO SANTANDER"},
  {"departamento"=>"Amazonas", "id"=>91798, "nombre"=>"TARAPAC?"},
  {"departamento"=>"Guainia", "id"=>94001, "nombre"=>"IN?RIDA"},
  {"departamento"=>"Guainia", "id"=>94343, "nombre"=>"BARRANCO MINAS"},
  {"departamento"=>"Guainia", "id"=>94663, "nombre"=>"MAPIRIPANA"},
  {"departamento"=>"Guainia", "id"=>94883, "nombre"=>"SAN FELIPE"},
  {"departamento"=>"Guainia", "id"=>94884, "nombre"=>"PUERTO COLOMBIA"},
  {"departamento"=>"Guainia", "id"=>94885, "nombre"=>"LA GUADALUPE"},
  {"departamento"=>"Guainia", "id"=>94886, "nombre"=>"CACAHUAL"},
  {"departamento"=>"Guainia", "id"=>94887, "nombre"=>"PANA PANA"},
  {"departamento"=>"Guainia", "id"=>94888, "nombre"=>"MORICHAL"},
  {"departamento"=>"Guaviare", "id"=>95001, "nombre"=>"SAN JOS? DEL GUAVIARE"},
  {"departamento"=>"Guaviare", "id"=>95015, "nombre"=>"CALAMAR"},
  {"departamento"=>"Guaviare", "id"=>95025, "nombre"=>"EL RETORNO"},
  {"departamento"=>"Guaviare", "id"=>95200, "nombre"=>"MIRAFLORES"},
  {"departamento"=>"Vaupes", "id"=>97001, "nombre"=>"MIT"},
  {"departamento"=>"Vaupes", "id"=>97161, "nombre"=>"CARURU"},
  {"departamento"=>"Vaupes", "id"=>97511, "nombre"=>"PACOA"},
  {"departamento"=>"Vaupes", "id"=>97666, "nombre"=>"TARAIRA"},
  {"departamento"=>"Vaupes", "id"=>97777, "nombre"=>"PAPUNAUA"},
  {"departamento"=>"Vaupes", "id"=>97889, "nombre"=>"YAVARAT?"},
  {"departamento"=>"Vichada", "id"=>99001, "nombre"=>"PUERTO CARRE?O"},
  {"departamento"=>"Vichada", "id"=>99524, "nombre"=>"LA PRIMAVERA"},
  {"departamento"=>"Vichada", "id"=>99624, "nombre"=>"SANTA ROSAL?A"},
  {"departamento"=>"Vichada", "id"=>99773, "nombre"=>"CUMARIBO"} 
]

Ciudad.create!(ciudades)
puts "Ciudades iniciales guardadas"

